DATA LIST FILE='C:\COUNTRIES\CI62\CIPR62FL.DAT' RECORDS=1
  /
  HHID        1-12   (A)
  HVIDX      13-14  
  HV000      15-17   (A)
  HV001      18-25  
  HV002      26-29  
  HV003      30-32  
  HV004      33-36  
  HV005      37-44  
  HV006      45-46  
  HV007      47-50  
  HV008      51-54  
  HV009      55-56  
  HV010      57-58  
  HV011      59-60  
  HV012      61-62  
  HV013      63-64  
  HV014      65-66  
  HV015      67-67  
  HV016      68-69  
  HV017      70-70  
  HV018      71-73  
  HV019      74-75  
  HV020      76-76  
  HV021      77-80  
  HV022      81-84  
  HV023      85-86  
  HV024      87-88  
  HV025      89-89  
  HV026      90-90  
  HV027      91-91  
  HV028      92-99  
  HV030     100-102 
  HV031     103-105 
  HV032     106-107 
  HV035     108-109 
  HV040     110-113 
  HV041     114-115 
  HV042     116-116 
  HV044     117-117 
  HV201     118-119 
  HV202     120-121 
  HV204     122-124 
  HV205     125-126 
  HV206     127-127 
  HV207     128-128 
  HV208     129-129 
  HV209     130-130 
  HV210     131-131 
  HV211     132-132 
  HV212     133-133 
  HV213     134-135 
  HV214     136-137 
  HV215     138-139 
  HV216     140-141 
  HV217     142-142 
  HV218     143-144 
  HV219     145-145 
  HV220     146-147 
  HV221     148-148 
  HV225     149-149 
  HV226     150-151 
  HV227     152-152 
  HV228     153-153 
  HV230A    154-154 
  HV230B    155-155 
  HV232     156-156 
  HV232B    157-157 
  HV232C    158-158 
  HV232D    159-159 
  HV232E    160-160 
  HV232Y    161-161 
  HV234     162-164 
  HV234A    165-165 
  HV235     166-166 
  HV236     167-167 
  HV237     168-168 
  HV237A    169-169 
  HV237B    170-170 
  HV237C    171-171 
  HV237D    172-172 
  HV237E    173-173 
  HV237F    174-174 
  HV237G    175-175 
  HV237H    176-176 
  HV237I    177-177 
  HV237J    178-178 
  HV237K    179-179 
  HV237X    180-180 
  HV237Z    181-181 
  HV238     182-183 
  HV239     184-184 
  HV240     185-185 
  HV241     186-186 
  HV242     187-187 
  HV243A    188-188 
  HV243B    189-189 
  HV243C    190-190 
  HV243D    191-191 
  HV244     192-192 
  HV245     193-195 
  HV246     196-196 
  HV246A    197-198 
  HV246B    199-200 
  HV246C    201-202 
  HV246D    203-204 
  HV246E    205-206 
  HV246F    207-208 
  HV246G    209-210 
  HV246H    211-212 
  HV246I    213-214 
  HV246J    215-216 
  HV246K    217-218 
  HV247     219-219 
  HV252     220-220 
  HV253     221-221 
  HV253A    222-222 
  HV253B    223-223 
  HV253C    224-224 
  HV253D    225-225 
  HV253E    226-226 
  HV253F    227-227 
  HV253G    228-228 
  HV253H    229-229 
  HV253X    230-230 
  HV253Z    231-231 
  HV270     232-232 
  HV271     233-240 
  HML1      241-242 
  HML1A     243-243 
  HML2      244-245 
  SHNUMDV   246-247 
  CHL0      248-249 
  SH106A    250-250 
  SH106B    251-251 
  SH106C    252-252 
  SH106X    253-253 
  SH106Z    254-254 
  SH107A    255-255 
  SH110G    256-256 
  SH110H    257-257 
  SH110I    258-258 
  SH110J    259-259 
  SH110K    260-260 
  SH110L    261-261 
  SH110M    262-262 
  SH110N    263-263 
  SH110O    264-264 
  SH118B    265-265 
  SH118F    266-266 
  SH118G    267-267 
  HV101     268-269 
  HV102     270-270 
  HV103     271-271 
  HV104     272-272 
  HV105     273-274 
  HV106     275-275 
  HV107     276-277 
  HV108     278-279 
  HV109     280-280 
  HV110     281-281 
  HV111     282-282 
  HV112     283-284 
  HV113     285-285 
  HV114     286-287 
  HV115     288-288 
  HV116     289-289 
  HV117     290-290 
  HV118     291-291 
  HV120     292-292 
  HV121     293-293 
  HV122     294-294 
  HV123     295-296 
  HV124     297-298 
  HV125     299-299 
  HV126     300-300 
  HV127     301-302 
  HV128     303-304 
  HV129     305-305 
  HV140     306-306 
  IDXH4     307-308 
  SH16      309-309 
  SH17A     310-310 
  SH17B     311-311 
  SH18      312-312 
  SH19A     313-313 
  SH19B     314-314 
  SH21      315-315 
  SH716C    316-316 
  SH816C    317-317 
  HA0       318-319 
  HA1       320-321 
  HA2       322-325 
  HA3       326-329 
  HA4       330-333 
  HA5       334-337 
  HA6       338-342 
  HA11      343-346 
  HA12      347-351 
  HA12A     352-356 
  HA12B     357-361 
  HA13      362-362 
  HA32      363-366 
  HA33      367-367 
  HA35      368-369 
  HA40      370-373 
  HA41      374-377 
  HA50      378-378 
  HA51      379-380 
  HA52      381-381 
  HA53      382-384 
  HA54      385-385 
  HA55      386-386 
  HA56      387-389 
  HA57      390-390 
  HA58      391-391 
  HA60      392-392 
  HA61      393-393 
  HA62      394-398  (A)
  HA63      399-399 
  HA64      400-400 
  HA65      401-401 
  HA66      402-402 
  HA67      403-404 
  HA68      405-405 
  HA69      406-413 
  HA70      414-416 
  HC0       417-418 
  HC1       419-420 
  HC2       421-424 
  HC3       425-428 
  HC4       429-432 
  HC5       433-436 
  HC6       437-441 
  HC7       442-445 
  HC8       446-449 
  HC9       450-454 
  HC10      455-458 
  HC11      459-462 
  HC12      463-467 
  HC13      468-468 
  HC15      469-469 
  HC16      470-471 
  HC17      472-473 
  HC18      474-475 
  HC19      476-479 
  HC27      480-480 
  HC30      481-482 
  HC31      483-486 
  HC32      487-490 
  HC33      491-491 
  HC51      492-493 
  HC52      494-494 
  HC53      495-497 
  HC55      498-498 
  HC56      499-501 
  HC57      502-502 
  HC58      503-503 
  HC60      504-506 
  HC61      507-507 
  HC62      508-509 
  HC63      510-512 
  HC64      513-514 
  HC68      515-515 
  HC70      516-519 
  HC71      520-523 
  HC72      524-527 
  HC73      528-531 
  HB0       532-533 
  HB1       534-535 
  HB2       536-539 
  HB3       540-543 
  HB4       544-547 
  HB5       548-551 
  HB6       552-556 
  HB11      557-560 
  HB12      561-565 
  HB12A     566-570 
  HB12B     571-575 
  HB13      576-576 
  HB32      577-580 
  HB33      581-581 
  HB35      582-583 
  HB40      584-587 
  HB41      588-591 
  HB50      592-592 
  HB51      593-594 
  HB52      595-595 
  HB53      596-598 
  HB55      599-599 
  HB56      600-602 
  HB57      603-603 
  HB58      604-604 
  HB60      605-605 
  HB61      606-606 
  HB62      607-611  (A)
  HB63      612-612 
  HB64      613-613 
  HB65      614-614 
  HB66      615-615 
  HB67      616-617 
  HB68      618-618 
  HB69      619-626 
  HB70      627-629 
  HMLIDX    630-631 
  HML3      632-632 
  HML4      633-634 
  HML5      635-635 
  HML6      636-636 
  HML7      637-638 
  HML8      639-639 
  HML9      640-641 
  HML10     642-642 
  HML11     643-643 
  HML21     644-644 
  HMLA      645-646 
  HMLB      647-648 
  HMLC      649-650 
  HMLD      651-652 
  HMLE      653-654 
  HMHIDX    655-656 
  HML12     657-657 
  HML13     658-658 
  HML14     659-659 
  HML15     660-660 
  HML16     661-662 
  HML16A    663-664 
  HML17     665-665 
  HML18     666-666 
  HML19     667-667 
  HML20     668-668 
  HML30     669-670 
  HML31     671-671 
  HML32     672-672 
  HML32A    673-673 
  HML32B    674-674 
  HML32C    675-675 
  HML32D    676-676 
  HML32E    677-677 
  HML32F    678-678 
  HML32G    679-679 
  HML33     680-680 
  HML34     681-685  (A)
  HML35     686-686 
  IDXCHL    687-688 
  CHL1      689-689 
  CHL2      690-691 
  CHL3      692-692 
  CHL4      693-694 
  CHL5      695-695 
  CHL6      696-697 
  CHL7      698-698 
  CHL8      699-700 
 .
VARIABLE LABELS
   HHID     "Case Identification"
  /HVIDX    "Line number"
  /HV000    "Country code and phase"
  /HV001    "Cluster number"
  /HV002    "Household number"
  /HV003    "Respondent's line number (answering Household questionnaire)"
  /HV004    "Ultimate area unit"
  /HV005    "Household sample weight (6 decimals)"
  /HV006    "Month of interview"
  /HV007    "Year of interview"
  /HV008    "Date of interview (CMC)"
  /HV009    "Number of household members"
  /HV010    "Number of eligible women in household"
  /HV011    "Number of eligible men in household"
  /HV012    "Number of de jure members"
  /HV013    "Number of de facto members"
  /HV014    "Number of children 5 and under (de jure)"
  /HV015    "Result of household interview"
  /HV016    "Day of interview"
  /HV017    "Number of visits"
  /HV018    "Interviewer identification"
  /HV019    "Keyer identification"
  /HV020    "Ever-married sample"
  /HV021    "Primary sampling unit"
  /HV022    "Sample strata for sampling errors"
  /HV023    "Stratification used in sample design"
  /HV024    "Region"
  /HV025    "Type of place of residence"
  /HV026    "Place of residence"
  /HV027    "Household selected for male interview"
  /HV028    "Household weight for male subsample (6 decimals)"
  /HV030    "Field supervisor"
  /HV031    "Field editor"
  /HV032    "Office editor"
  /HV035    "Number of eligible children for height and weight"
  /HV040    "Cluster altitude in meters"
  /HV041    "Total adults measured"
  /HV042    "Household selected for hemoglobin"
  /HV044    "Household selected for Domestic Violence module"
  /HV201    "Source of drinking water"
  /HV202    "NA - Source of non-drinking water"
  /HV204    "Time to get to water source (minutes)"
  /HV205    "Type of toilet facility"
  /HV206    "Has electricity"
  /HV207    "Has radio"
  /HV208    "Has television"
  /HV209    "Has refrigerator"
  /HV210    "Has bicycle"
  /HV211    "Has motorcycle/scooter"
  /HV212    "Has car/truck"
  /HV213    "Main floor material"
  /HV214    "Main wall material"
  /HV215    "Main roof material"
  /HV216    "Number of rooms used for sleeping"
  /HV217    "Relationship structure"
  /HV218    "Line number of head of household"
  /HV219    "Sex of head of household"
  /HV220    "Age of head of household"
  /HV221    "Has telephone (land-line)"
  /HV225    "Share toilet with other households"
  /HV226    "Type of cooking fuel"
  /HV227    "Has mosquito bed net for sleeping"
  /HV228    "Children under 5 slept under mosquito bed net last night"
  /HV230A   "Place where household members wash their hands"
  /HV230B   "Presence of water at hand washing place"
  /HV232    "Items present: Soap or detergent"
  /HV232B   "Items present: Ash, mud, sand"
  /HV232C   "NA - Items present: CS"
  /HV232D   "NA - Items present: CS"
  /HV232E   "NA - Items present: CS"
  /HV232Y   "Items present: None"
  /HV234    "NA - Result of salt test for iodine (PPM)"
  /HV234A   "Result of salt test for iodine"
  /HV235    "Location of source for water"
  /HV236    "NA - Person fetching water"
  /HV237    "Anything done to water to make safe to drink"
  /HV237A   "Water usually treated by: boil"
  /HV237B   "Water usually treated by: add bleach/chlorine"
  /HV237C   "Water usually treated by: strain through a cloth"
  /HV237D   "Water usually treated by: use water filter"
  /HV237E   "Water usually treated by: solar disinfection"
  /HV237F   "Water usually treated by: let it stand and settle"
  /HV237G   "NA - Water usually treated by: CS"
  /HV237H   "NA - Water usually treated by: CS"
  /HV237I   "NA - Water usually treated by: CS"
  /HV237J   "NA - Water usually treated by: CS"
  /HV237K   "NA - Water usually treated by: CS"
  /HV237X   "Water usually treated by: other"
  /HV237Z   "Water usually treated by: don't know"
  /HV238    "Number of households sharing toilet"
  /HV239    "Food cooked on stove or open fire"
  /HV240    "Household has a chimney, hood or neither"
  /HV241    "Food cooked in the house/ separate building/ outdoors"
  /HV242    "Household has separate room used as kitchen"
  /HV243A   "Has mobile telephone"
  /HV243B   "Has watch"
  /HV243C   "Has animal-drawn cart"
  /HV243D   "Has boat with a motor"
  /HV244    "Owns land usable for agriculture"
  /HV245    "Hectares of agricultural land (1 decimal)"
  /HV246    "Owns livestock, herds or farm animals"
  /HV246A   "Owns cattle"
  /HV246B   "Owns cows/ bulls"
  /HV246C   "Owns horses/ donkeys/ mules"
  /HV246D   "Owns goats"
  /HV246E   "Owns sheep"
  /HV246F   "Owns chickens"
  /HV246G   "Owns pigs"
  /HV246H   "NA - Owns CS"
  /HV246I   "NA - Owns CS"
  /HV246J   "NA - Owns CS"
  /HV246K   "NA - Owns CS"
  /HV247    "Has bank account"
  /HV252    "Frequency household members smoke inside the house"
  /HV253    "Has dwelling been sprayed against mosquitoes in last 12 months"
  /HV253A   "Dwelling sprayed by: government worker/program"
  /HV253B   "Dwelling sprayed by: private company"
  /HV253C   "Dwelling sprayed by: NGO"
  /HV253D   "NA - Dwelling sprayed by: CS"
  /HV253E   "NA - Dwelling sprayed by: CS"
  /HV253F   "NA - Dwelling sprayed by: CS"
  /HV253G   "NA - Dwelling sprayed by: CS"
  /HV253H   "NA - Dwelling sprayed by: CS"
  /HV253X   "Dwelling sprayed by: other"
  /HV253Z   "Dwelling sprayed by: don't know"
  /HV270    "Wealth index"
  /HV271    "Wealth index factor score (5 decimals)"
  /HML1     "Number of mosquito bed nets"
  /HML1A    "Number of mosquito bed nets with specific information"
  /HML2     "Number of children under mosquito bed net previous night"
  /SHNUMDV  "Line number of domestic violence respondent"
  /CHL0     "Number of de-jure children 5-14 for child labor module"
  /SH106A   "Drinking water stored in: open container"
  /SH106B   "Drinking water stored in: closed container"
  /SH106C   "Drinking water stored in: flasks or bottles"
  /SH106X   "Drinking water stored in: other"
  /SH106Z   "Drinking water stored in: don't know"
  /SH107A   "Location of toilets"
  /SH110G   "Owns TV5 antenna"
  /SH110H   "Owns cable subscription"
  /SH110I   "Owns washing machine"
  /SH110J   "Owns stove or burner"
  /SH110K   "Owns improved woodstove"
  /SH110L   "Owns CD/DVD player"
  /SH110M   "Owns air-conditioner"
  /SH110N   "Owns computer"
  /SH110O   "Owns home internet connection"
  /SH118B   "Owns plow"
  /SH118F   "Owns fishing equipment"
  /SH118G   "Owns tractor"
  /HV101    "Relationship to head"
  /HV102    "Usual resident"
  /HV103    "Slept last night"
  /HV104    "Sex of household member"
  /HV105    "Age of household members"
  /HV106    "Highest educational level attained"
  /HV107    "Highest year of education completed"
  /HV108    "Education completed in single years"
  /HV109    "Educational attainment"
  /HV110    "NA - Member still in school"
  /HV111    "Mother alive"
  /HV112    "Mother's line number"
  /HV113    "Father alive"
  /HV114    "Father's line number"
  /HV115    "Current marital status"
  /HV116    "Currently, formerly, never married"
  /HV117    "Eligibility for female interview"
  /HV118    "Eligibility for male interview"
  /HV120    "Children eligibility for height/weight and hemoglobin"
  /HV121    "Member attended school during current school year"
  /HV122    "Educational level during current school year"
  /HV123    "Grade of education during current school year"
  /HV124    "Education in single years - current school year"
  /HV125    "NA - Member attended school during previous school year"
  /HV126    "NA - Educational level during previous school year"
  /HV127    "NA - Grade of education during previous school year"
  /HV128    "NA - Education in single years - previous school year"
  /HV129    "NA - School attendance status"
  /HV140    "Member has a birth certificate"
  /IDXH4    "Index to Household Schedule"
  /SH16     "Ever attended school"
  /SH17A    "Highest education level"
  /SH17B    "Highest class attained at that level"
  /SH18     "Attended school current year"
  /SH19A    "Level currently attending"
  /SH19B    "Class currently attending"
  /SH21     "Has health insurance coverage"
  /SH716C   "Consent for counseling and further testing (women)"
  /SH816C   "Consent for counseling and further testing (men)"
  /HA0      "Index to Household Schedule"
  /HA1      "Woman's age in years"
  /HA2      "Woman's weight in kilograms (1 decimal)"
  /HA3      "Woman's height in centimeters (1 decimal)"
  /HA4      "Height/Age percentile"
  /HA5      "Height/Age standard deviation"
  /HA6      "Height/Age percent ref. median"
  /HA11     "Weight/Height standard deviation (DHS)"
  /HA12     "Weight/Height percent ref. median (DHS)"
  /HA12A    "Weight/Height percent ref. median (Fog)"
  /HA12B    "Weight/Height percent ref. median (WHO)"
  /HA13     "Result of measurement - height/weight"
  /HA32     "Date of birth (CMC)"
  /HA33     "Completeness of HA32 information"
  /HA35     "Smoking (cigarettes in last 24 hours)"
  /HA40     "Body Mass Index"
  /HA41     "Rohrer's index"
  /HA50     "Under age 18"
  /HA51     "Line number of parent/caretaker"
  /HA52     "Read consent statement - hemoglobin"
  /HA53     "Hemoglobin level (g/dl - 1 decimal)"
  /HA54     "Currently pregnant"
  /HA55     "Result of measurement - hemoglobin"
  /HA56     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
  /HA57     "Anemia level"
  /HA58     "NA - Agrees to referral - anemia"
  /HA60     "Marital status"
  /HA61     "Read consent statement - HIV"
  /HA62     "Bar code for HIV blood sample"
  /HA63     "Result of measurement - HIV"
  /HA64     "NA - Consent for additional tests"
  /HA65     "Result of woman's individual interview"
  /HA66     "Woman's highest educational level"
  /HA67     "Woman's highest year of education"
  /HA68     "Woman's highest educational level (questionnaire configuration)"
  /HA69     "HIV weight (6 decimals)"
  /HA70     "NA - Interviewer that took blood for HIV testing"
  /HC0      "Index to Household Schedule"
  /HC1      "Child's age in months"
  /HC2      "Child's weight in kilograms (1 decimal)"
  /HC3      "Child's height in centimeters (1 decimal)"
  /HC4      "Height/Age percentile"
  /HC5      "Height/Age standard deviation"
  /HC6      "Height/Age percent of ref. median"
  /HC7      "Weight/Age percentile"
  /HC8      "Weight/Age standard deviation"
  /HC9      "Weight/Age percent of ref. median"
  /HC10     "Weight/Height percentile"
  /HC11     "Weight/Height standard deviation"
  /HC12     "Weight/Height percent of ref. median"
  /HC13     "Result of measurement - height/weight"
  /HC15     "Height: lying or standing"
  /HC16     "Day of birth"
  /HC17     "Date measured (day)"
  /HC18     "Date measured (month)"
  /HC19     "Date measured (year)"
  /HC27     "Sex"
  /HC30     "Month of birth"
  /HC31     "Year of birth"
  /HC32     "Date of birth (CMC)"
  /HC33     "Completeness of HC32 information"
  /HC51     "Line number of parent/caretaker"
  /HC52     "Read consent statement - hemoglobin"
  /HC53     "Hemoglobin level (g/dl - 1 decimal)"
  /HC55     "Result of measurement - hemoglobin"
  /HC56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
  /HC57     "Anemia level"
  /HC58     "NA - Agrees to referral - anemia"
  /HC60     "Mother's line number (woman's questionnaire)"
  /HC61     "Mother's highest educational level"
  /HC62     "Mother's highest year of education"
  /HC63     "Preceding birth interval (months)"
  /HC64     "Birth order number"
  /HC68     "Mother's highest educational level (questionnaire configuration)"
  /HC70     "Height/Age standard deviation (new WHO)"
  /HC71     "Weight/Age standard deviation (new WHO)"
  /HC72     "Weight/Height standard deviation (new WHO)"
  /HC73     "BMI standard deviation (new WHO)"
  /HB0      "Index to Household Schedule"
  /HB1      "Man's age in years"
  /HB2      "NA - Man's weight in kilograms (1 decimal)"
  /HB3      "NA - Man's height in centimeters (1 decimal)"
  /HB4      "NA - Height/Age percentile"
  /HB5      "NA - Height/Age standard deviation"
  /HB6      "NA - Height/Age percent ref. median"
  /HB11     "NA - Weight/Height standard deviation (DHS)"
  /HB12     "NA - Weight/Height percent ref. median (DHS)"
  /HB12A    "NA - Weight/Height percent ref. median (Fog)"
  /HB12B    "NA - Weight/Height percent ref. median (WHO)"
  /HB13     "NA - Result of measurement - height/weight"
  /HB32     "Date of birth (CMC)"
  /HB33     "Completeness of HB32 information"
  /HB35     "Smoking (cigarettes in last 24 hours)"
  /HB40     "NA - Body Mass Index"
  /HB41     "NA - Rohrer's index"
  /HB50     "Under age 18"
  /HB51     "Line number of parent/caretaker"
  /HB52     "Read consent statement - hemoglobin"
  /HB53     "Hemoglobin level (g/dl - 1 decimal)"
  /HB55     "Result of measurement - hemoglobin"
  /HB56     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
  /HB57     "Anemia level"
  /HB58     "NA - Agrees to referral - anemia"
  /HB60     "Marital status"
  /HB61     "Read consent statement - HIV"
  /HB62     "Bar code for HIV blood sample"
  /HB63     "Result of measurement - HIV"
  /HB64     "NA - Consent for additional tests"
  /HB65     "Result of man's individual interview"
  /HB66     "Man's highest educational level"
  /HB67     "Man's highest year of education"
  /HB68     "Man's highest educational level (questionnaire configuration)"
  /HB69     "HIV weight (6 decimals)"
  /HB70     "NA - Interviewer that took blood for HIV testing"
  /HMLIDX   "Mosquito Bed Net Designation Number"
  /HML3     "Net observed by interviewer"
  /HML4     "Months ago net obtained"
  /HML5     "Net treated with insecticide when bought"
  /HML6     "Net treatment status"
  /HML7     "Brand of net"
  /HML8     "Net treated since receiving"
  /HML9     "Time since last re-treatment (months)"
  /HML10    "Insecticide-Treated Net (ITN)"
  /HML11    "Number of persons who slept under this net"
  /HML21    "Someone slept under this net last night"
  /HMLA     "Line number of person who slept in this net"
  /HMLB     "Line number of person who slept in this net"
  /HMLC     "Line number of person who slept in this net"
  /HMLD     "Line number of person who slept in this net"
  /HMLE     "NA - Line number of person who slept in this net"
  /HMHIDX   "Index to Household Schedule"
  /HML12    "Type of Mosquito Bed Net(s) person slept under last night"
  /HML13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
  /HML14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
  /HML15    "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
  /HML16    "Corrected age from Individual file"
  /HML16A   "Age in months (for children)"
  /HML17    "Flag for age from Individual file"
  /HML18    "Pregnancy status from Individual file"
  /HML19    "Person slept under an ever-treated net"
  /HML20    "Person slept under an LLIN net"
  /HML30    "Line number of parent/caretaker (for malaria testing)"
  /HML31    "Read consent statement for malaria"
  /HML32    "Final result of malaria from blood smear test"
  /HML32A   "Presence of species: falciparum (Pf)"
  /HML32B   "Presence of species: malariae (Pm)"
  /HML32C   "Presence of species: ovale (Po)"
  /HML32D   "Presence of species: vivax (Pv)"
  /HML32E   "NA - Presence of species: CS"
  /HML32F   "NA - Presence of species: CS"
  /HML32G   "NA - Presence of species: CS"
  /HML33    "Result of malaria measurement"
  /HML34    "Bar code for blood smear sample"
  /HML35    "Result of malaria rapid test"
  /IDXCHL   "Index to household schedule"
  /CHL1     "Worked for someone outside household"
  /CHL2     "Hours worked for someone outside household"
  /CHL3     "Fetched wood or water"
  /CHL4     "Hours spent fetching wood or water"
  /CHL5     "Worked for a family member"
  /CHL6     "Hours spent working for family member"
  /CHL7     "Did domestic household work"
  /CHL8     "Hours spent doing domestic household work"
 .
MISSING VALUE
   HV017    (9)
  /HV018    (999)
  /HV026    (9)
  /HV030    (999)
  /HV040    (9999)
  /HV201    (99)
  /HV202    (99)
  /HV204    (999)
  /HV205    (99)
  /HV206    (9)
  /HV207    (9)
  /HV208    (9)
  /HV209    (9)
  /HV210    (9)
  /HV211    (9)
  /HV212    (9)
  /HV213    (99)
  /HV214    (99)
  /HV215    (99)
  /HV216    (99)
  /HV219    (9)
  /HV220    (99)
  /HV221    (9)
  /HV225    (9)
  /HV226    (99)
  /HV227    (9)
  /HV228    (9)
  /HV230A   (9)
  /HV230B   (9)
  /HV232    (9)
  /HV232B   (9)
  /HV232C   (9)
  /HV232D   (9)
  /HV232E   (9)
  /HV232Y   (9)
  /HV234    (999)
  /HV234A   (9)
  /HV235    (9)
  /HV236    (9)
  /HV237    (9)
  /HV237A   (9)
  /HV237B   (9)
  /HV237C   (9)
  /HV237D   (9)
  /HV237E   (9)
  /HV237F   (9)
  /HV237G   (9)
  /HV237H   (9)
  /HV237I   (9)
  /HV237J   (9)
  /HV237K   (9)
  /HV237X   (9)
  /HV237Z   (9)
  /HV238    (99)
  /HV239    (9)
  /HV240    (9)
  /HV241    (9)
  /HV242    (9)
  /HV243A   (9)
  /HV243B   (9)
  /HV243C   (9)
  /HV243D   (9)
  /HV244    (9)
  /HV245    (999)
  /HV246    (9)
  /HV246A   (99)
  /HV246B   (99)
  /HV246C   (99)
  /HV246D   (99)
  /HV246E   (99)
  /HV246F   (99)
  /HV246G   (99)
  /HV246H   (99)
  /HV246I   (99)
  /HV246J   (99)
  /HV246K   (99)
  /HV247    (9)
  /HV252    (9)
  /HV253    (9)
  /HV253A   (9)
  /HV253B   (9)
  /HV253C   (9)
  /HV253D   (9)
  /HV253E   (9)
  /HV253F   (9)
  /HV253G   (9)
  /HV253H   (9)
  /HV253X   (9)
  /HV253Z   (9)
  /HML1     (99)
  /HML2     (99)
  /SHNUMDV  (99)
  /SH106A   (9)
  /SH106B   (9)
  /SH106C   (9)
  /SH106X   (9)
  /SH106Z   (9)
  /SH107A   (9)
  /SH110G   (9)
  /SH110H   (9)
  /SH110I   (9)
  /SH110J   (9)
  /SH110K   (9)
  /SH110L   (9)
  /SH110M   (9)
  /SH110N   (9)
  /SH110O   (9)
  /SH118B   (9)
  /SH118F   (9)
  /SH118G   (9)
  /HV101    (99)
  /HV102    (9)
  /HV103    (9)
  /HV104    (9)
  /HV105    (99)
  /HV106    (9)
  /HV107    (99)
  /HV108    (99)
  /HV109    (9)
  /HV110    (9)
  /HV111    (9)
  /HV112    (99)
  /HV113    (9)
  /HV114    (99)
  /HV115    (9)
  /HV116    (9)
  /HV121    (9)
  /HV122    (9)
  /HV123    (99)
  /HV124    (99)
  /HV125    (9)
  /HV126    (9)
  /HV127    (99)
  /HV128    (99)
  /HV129    (9)
  /HV140    (9)
  /SH16     (9)
  /SH17A    (9)
  /SH17B    (9)
  /SH18     (9)
  /SH19A    (9)
  /SH19B    (9)
  /SH21     (9)
  /SH716C   (9)
  /SH816C   (9)
  /HA2      (9999)
  /HA3      (9999)
  /HA4      (9999)
  /HA5      (9999)
  /HA6      (99999)
  /HA11     (9999)
  /HA12     (99999)
  /HA12A    (99999)
  /HA12B    (99999)
  /HA13     (9)
  /HA35     (99)
  /HA40     (9999)
  /HA41     (9999)
  /HA50     (9)
  /HA51     (99)
  /HA52     (9)
  /HA53     (999)
  /HA54     (9)
  /HA55     (9)
  /HA56     (999)
  /HA57     (9)
  /HA58     (9)
  /HA60     (9)
  /HA61     (9)
  /HA63     (9)
  /HA64     (9)
  /HA66     (9)
  /HA67     (99)
  /HA68     (9)
  /HA70     (999)
  /HC2      (9999)
  /HC3      (9999)
  /HC4      (9999)
  /HC5      (9999)
  /HC6      (99999)
  /HC7      (9999)
  /HC8      (9999)
  /HC9      (99999)
  /HC10     (9999)
  /HC11     (9999)
  /HC12     (99999)
  /HC13     (9)
  /HC15     (9)
  /HC16     (99)
  /HC27     (9)
  /HC30     (99)
  /HC31     (9999)
  /HC51     (99)
  /HC52     (9)
  /HC53     (999)
  /HC55     (9)
  /HC56     (999)
  /HC57     (9)
  /HC58     (9)
  /HC60     (999)
  /HC61     (9)
  /HC62     (99)
  /HC63     (999)
  /HC64     (99)
  /HC68     (9)
  /HC70     (9999)
  /HC71     (9999)
  /HC72     (9999)
  /HC73     (9999)
  /HB2      (9999)
  /HB3      (9999)
  /HB4      (9999)
  /HB5      (9999)
  /HB6      (99999)
  /HB11     (9999)
  /HB12     (99999)
  /HB12A    (99999)
  /HB12B    (99999)
  /HB13     (9)
  /HB35     (99)
  /HB40     (9999)
  /HB41     (9999)
  /HB50     (9)
  /HB51     (99)
  /HB52     (9)
  /HB53     (999)
  /HB55     (9)
  /HB56     (999)
  /HB57     (9)
  /HB58     (9)
  /HB60     (9)
  /HB61     (9)
  /HB63     (9)
  /HB64     (9)
  /HB66     (9)
  /HB67     (99)
  /HB68     (9)
  /HB70     (999)
  /HML3     (9)
  /HML4     (99)
  /HML5     (9)
  /HML6     (9)
  /HML7     (99)
  /HML8     (9)
  /HML9     (99)
  /HML10    (9)
  /HML11    (9)
  /HML21    (9)
  /HMLA     (99)
  /HMLB     (99)
  /HMLC     (99)
  /HML12    (9)
  /HML16    (99)
  /HML18    (9)
  /HML30    (99)
  /HML31    (9)
  /HML32    (9)
  /HML32A   (9)
  /HML32B   (9)
  /HML32C   (9)
  /HML32D   (9)
  /HML32E   (9)
  /HML32F   (9)
  /HML32G   (9)
  /HML33    (9)
  /HML35    (9)
  /CHL1     (9)
  /CHL2     (99)
  /CHL3     (9)
  /CHL4     (99)
  /CHL5     (9)
  /CHL6     (99)
  /CHL7     (9)
  /CHL8     (99)
 .
VALUE LABELS
   HV003   
      0 "Incomplete household"
  /HV015   
      1 "Completed"
      2 "No Household member/no competent member at home"
      3 "Entire Household absent for extended period of time"
      4 "Postponed"
      5 "Refused"
      6 "Dwelling vacant or address not a dwelling"
      7 "Dwelling destroyed"
      8 "Dwelling not found"
      9 "Other"
  /HV020   
      0 "All woman sample"
      1 "Ever married sample"
  /HV022   
      1 "Urban Centre"
      2 "Rural Centre"
      3 "Urban Centre-Est"
      4 "Rural Centre-Est"
      5 "Urban Centre-Nord"
      6 "Rural Centre-Nord"
      7 "Urban Centre-Ouest"
      8 "Rural Centre-Ouest"
      9 "Urban Nord"
     10 "Rural Nord"
     11 "Urban Nord-est"
     12 "Rural Nord-est"
     13 "Urban Nord-Ouest"
     14 "Rural Nord-Ouest"
     15 "Urban Ouest"
     16 "Rural Ouest"
     17 "Urban Sud sans Abidjan"
     18 "Rural Sud sans Abidjan"
     19 "Urban Sud-ouest"
     20 "Rural Sud-ouest"
     21 "Urban Ville d'Abidjan"
     22 "Rural Ville d'Abidjan"
  /HV023   
      1 "Urban Centre"
      2 "Rural Centre"
      3 "Urban Centre-Est"
      4 "Rural Centre-Est"
      5 "Urban Centre-Nord"
      6 "Rural Centre-Nord"
      7 "Urban Centre-Ouest"
      8 "Rural Centre-Ouest"
      9 "Urban Nord"
     10 "Rural Nord"
     11 "Urban Nord-est"
     12 "Rural Nord-est"
     13 "Urban Nord-Ouest"
     14 "Rural Nord-Ouest"
     15 "Urban Ouest"
     16 "Rural Ouest"
     17 "Urban Sud sans Abidjan"
     18 "Rural Sud sans Abidjan"
     19 "Urban Sud-ouest"
     20 "Rural Sud-ouest"
     21 "Urban Ville d'Abidjan"
     22 "Rural Ville d'Abidjan"
  /HV024   
      1 "Centre"
      2 "Centre-Est"
      3 "Centre-Nord"
      4 "Centre-Ouest"
      5 "Nord"
      6 "Nord-est"
      7 "Nord-Ouest"
      8 "Ouest"
      9 "Sud sans Abidjan"
     10 "Sud-ouest"
     11 "Ville d'Abidjan"
  /HV025   
      1 "Urban"
      2 "Rural"
  /HV026   
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /HV027   
      0 "Not selected"
      1 "Men's survey"
      2 "Husband's survey"
  /HV042   
      0 "Not selected"
      1 "Selected"
  /HV044   
      0 "Household not selected"
      1 "Household selected"
  /HV201   
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Public tap/standpipe"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE WATER"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     71 "Bottled water"
     96 "Other"
  /HV202   
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Public tap/standpipe"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE WATER"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     71 "Bottled water"
     96 "Other"
  /HV204   
    996 "On premises"
    998 "Don't know"
  /HV205   
     10 "FLUSH TOILET"
     11 "Flush to piped sewer system"
     12 "Flush to septic tank"
     13 "Flush to pit latrine"
     14 "Flush to somewhere else"
     15 "Flush, don't know where"
     20 "PIT TOILET LATRINE"
     21 "Ventilated Improved Pit latrine (VIP)"
     22 "Pit latrine with slab"
     23 "Pit latrine without slab/open pit"
     30 "NO FACILITY"
     31 "No facility/bush/field"
     41 "Composting toilet"
     42 "Bucket toilet"
     43 "Hanging toilet/latrine"
     96 "Other"
  /HV206   
      0 "No"
      1 "Yes"
  /HV207   
      0 "No"
      1 "Yes"
  /HV208   
      0 "No"
      1 "Yes"
  /HV209   
      0 "No"
      1 "Yes"
  /HV210   
      0 "No"
      1 "Yes"
  /HV211   
      0 "No"
      1 "Yes"
  /HV212   
      0 "No"
      1 "Yes"
  /HV213   
     10 "NATURAL"
     11 "Earth, sand"
     12 "Dung"
     20 "RUDIMENTARY"
     21 "Wood planks"
     22 "Palm, bamboo"
     30 "FINISHED"
     31 "Parquet, polished wood"
     32 "Vinyl, asphalt strips"
     33 "Ceramic tiles"
     34 "Cement"
     35 "Carpet"
     96 "Other"
  /HV214   
     10 "NATURAL"
     11 "No walls"
     12 "Cane/palm/trunks"
     13 "Dirt"
     20 "RUDIMENTARY"
     21 "Bamboo with mud"
     22 "Stone with mud"
     23 "Uncovered adobe"
     24 "Plywood"
     25 "Cardboard"
     26 "Reused wood"
     30 "FINISHED"
     31 "Cement"
     32 "Stone with lime/cement"
     33 "Bricks"
     34 "Cement blocks"
     35 "Covered adobe"
     36 "Wood planks/shingles"
     96 "Other"
  /HV215   
     10 "NATURAL"
     11 "No roof"
     12 "Thatch/palm leaf"
     13 "Sod"
     20 "RUDIMENTARY"
     21 "Rustic mat"
     22 "Palm/bamboo"
     23 "Wood planks"
     24 "Cardboard"
     30 "FINISHED"
     31 "Metal"
     32 "Wood"
     33 "Calamine/cement fiber"
     34 "Ceramic tiles"
     35 "Cement"
     36 "Roofing shingles"
     96 "Other"
  /HV217   
      0 "No adults"
      1 "One adult"
      2 "Two adults, opposite sex"
      3 "Two adults, same sex"
      4 "Three+ related adults"
      5 "Unrelated adults"
  /HV219   
      1 "Male"
      2 "Female"
  /HV220   
     95 "95+"
     98 "Don't know"
  /HV221   
      0 "No"
      1 "Yes"
  /HV225   
      0 "No"
      1 "Yes"
  /HV226   
      1 "Electricity"
      2 "LPG"
      3 "Natural gas"
      4 "Biogas"
      5 "Kerosene"
      6 "Coal, lignite"
      7 "Charcoal"
      8 "Wood"
      9 "Straw/shrubs/grass"
     10 "Agricultural crop"
     11 "Animal dung"
     95 "No food cooked in house"
     96 "Other"
  /HV227   
      0 "No"
      1 "Yes"
  /HV228   
      0 "No"
      1 "All children"
      2 "Some children"
      3 "No net in household"
  /HV230A  
      1 "Observed"
      2 "Not observed: not in dwelling"
      3 "Not observed: no permission to see"
      4 "Not observed: other reason"
  /HV230B  
      0 "Water not available"
      1 "Water is available"
  /HV232   
      0 "No"
      1 "Yes"
  /HV232B  
      0 "No"
      1 "Yes"
  /HV232C  
      0 "No"
      1 "Yes"
  /HV232D  
      0 "No"
      1 "Yes"
  /HV232E  
      0 "No"
      1 "Yes"
  /HV232Y  
      0 "No"
      1 "Yes: no cleansing agent observed"
  /HV234   
      0 "0 PPM (no iodine)"
      7 "Below 15 PPM"
     15 "15 PPM and above"
     30 "30 PPM"
    994 "Salt not tested"
    995 "No salt in household"
  /HV234A  
      0 "No iodine"
      1 "Iodine present"
      3 "No salt in household"
      6 "Salt not tested"
  /HV235   
      1 "In own dwelling"
      2 "In own yard/plot"
      3 "Elsewhere"
  /HV236   
      1 "Adult woman"
      2 "Adult man"
      3 "Female child under 15 years old"
      4 "Male child under 15 years old"
      6 "Other"
  /HV237   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237H  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237I  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237J  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237K  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237X  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV237Z  
      0 "No"
      1 "Yes: don't know what is done to water"
      8 "Don't know"
  /HV238   
     95 "10 or more households"
     98 "Don't know"
  /HV239   
      1 "Open fire"
      2 "Open stove"
      3 "Closed stove with chimney"
      6 "Other"
  /HV240   
      0 "Neither chimney or hood"
      1 "Chimney"
      2 "Hood"
  /HV241   
      1 "In the house"
      2 "In a separate building"
      3 "Outdoors"
      6 "Other"
  /HV242   
      0 "No"
      1 "Yes"
  /HV243A  
      0 "No"
      1 "Yes"
  /HV243B  
      0 "No"
      1 "Yes"
  /HV243C  
      0 "No"
      1 "Yes"
  /HV243D  
      0 "No"
      1 "Yes"
  /HV244   
      0 "No"
      1 "Yes"
  /HV245   
    950 "95 or more"
    998 "Unknown"
  /HV246   
      0 "No"
      1 "Yes"
  /HV246A  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246B  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246C  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246D  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246E  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246F  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246G  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246H  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246I  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246J  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV246K  
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /HV247   
      0 "No"
      1 "Yes"
  /HV252   
      0 "Never"
      1 "Daily"
      2 "Weekly"
      3 "Monthly"
      4 "Less than monthly"
  /HV253   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253H  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253X  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV253Z  
      0 "No"
      1 "Yes: don't know who sprayed the dwelling"
      8 "Don't know if it was sprayed"
  /HV270   
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /HML1    
     98 "Don't know"
  /SH106A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SH106B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SH106C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SH106X  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SH106Z  
      0 "No"
      1 "Yes: don't know storage"
      8 "Don't know"
  /SH107A  
      1 "In own dwelling"
      2 "In own yard/plot"
      3 "Elsewhere"
  /SH110G  
      0 "No"
      1 "Yes"
  /SH110H  
      0 "No"
      1 "Yes"
  /SH110I  
      0 "No"
      1 "Yes"
  /SH110J  
      0 "No"
      1 "Yes"
  /SH110K  
      0 "No"
      1 "Yes"
  /SH110L  
      0 "No"
      1 "Yes"
  /SH110M  
      0 "No"
      1 "Yes"
  /SH110N  
      0 "No"
      1 "Yes"
  /SH110O  
      0 "No"
      1 "Yes"
  /SH118B  
      0 "No"
      1 "Yes"
  /SH118F  
      0 "No"
      1 "Yes"
  /SH118G  
      0 "No"
      1 "Yes"
  /HV101   
      1 "Head"
      2 "Wife or husband"
      3 "Son/daughter"
      4 "Son/daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother/sister"
      9 "Co-spouse"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     13 "Niece/nephew by blood"
     14 "Niece/nephew by marriage"
     98 "Don't know"
  /HV102   
      0 "No"
      1 "Yes"
  /HV103   
      0 "No"
      1 "Yes"
  /HV104   
      1 "Male"
      2 "Female"
  /HV105   
     95 "95+"
     98 "Don't know"
  /HV106   
      0 "No education, preschool"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HV107   
     98 "Don't know"
  /HV108   
     97 "Inconsistent"
     98 "Don't know"
  /HV109   
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
      8 "Don't know"
  /HV110   
      0 "No"
      1 "Yes"
  /HV111   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV112   
      0 "Mother not in household"
  /HV113   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HV114   
      0 "Father not in household"
  /HV115   
      0 "Never married"
      1 "Married"
      2 "Living together"
      3 "Widowed"
      4 "Divorced/separated"
      5 "Not living together"
  /HV116   
      0 "Never married"
      1 "Currently married"
      2 "Formerly/ever married"
  /HV117   
      0 "Not eligible"
      1 "Eligible"
  /HV118   
      0 "Not eligible"
      1 "Eligible"
  /HV120   
      0 "Not eligible"
      1 "Eligible"
  /HV121   
      0 "No"
      1 "Currently attending"
      2 "Attended at some time"
  /HV122   
      0 "No education, preschool"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HV123   
     98 "Don't know"
  /HV124   
     97 "Inconsistent"
     98 "Don't know"
  /HV125   
      0 "No"
      1 "Yes"
  /HV126   
      0 "No education, preschool"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HV127   
     98 "Don't know"
  /HV128   
     97 "Inconsistent"
     98 "Don't know"
  /HV129   
      0 "Never attended"
      1 "Entered school"
      2 "Advanced"
      3 "Repeating"
      4 "Dropout"
      5 "Left school 2+ years ago"
      8 "Don't know"
  /HV140   
      0 "Neither certificate or registered"
      1 "Has certificate"
      2 "Registered"
      8 "Don't know"
  /SH16    
      0 "No"
      1 "Yes"
  /SH17A   
      0 "Pre-primary"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /SH17B   
      0 "Less than a year completed"
      8 "Don't know"
  /SH18    
      0 "No"
      1 "Yes"
  /SH19A   
      0 "Pre-primary"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /SH19B   
      0 "Less than a year completed"
      8 "Don't know"
  /SH21    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SH716C  
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /SH816C  
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HA2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HA3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HA4     
   9998 "Flagged cases"
  /HA5     
   9998 "Flagged cases"
  /HA6     
   99998 "Flagged cases"
  /HA11    
   9998 "Flagged cases"
  /HA12    
   99998 "Flagged cases"
  /HA12A   
   99998 "Flagged cases"
  /HA12B   
   99998 "Flagged cases"
  /HA13    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HA33    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HA35    
      0 "Doesn't smoke"
     80 "80+"
     94 "Smokes pipes, cigars, etc"
  /HA40    
   9998 "Flagged cases"
  /HA41    
   9998 "Flagged cases"
  /HA50    
      1 "Under age 18"
      2 "Age 18 or older"
  /HA51    
      0 "Not in household"
  /HA52    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HA53    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /HA54    
      0 "No/don't know"
      1 "Yes"
  /HA55    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HA57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HA58    
      0 "No"
      1 "Yes"
  /HA60    
      1 "Never in union"
      2 "Other"
  /HA61    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Sample not tested/lost/not enough DBS"
  /HA62    
   99993 "Sample damaged/insufficient/not found in lab"
   99994 "Not present"
   99995 "Refused"
   99996 "Other"
   '?    ' "Missing"
  /HA63    
      1 "Blood taken"
      2 "Not present"
      3 "Refused"
      4 "Sample not tested/lost/damaged/insufficient"
      5 "Not enough DBS to complete protocol"
      6 "Other"
  /HA64    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HA65    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /HA66    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HA68    
      0 "No education"
      1 "Primary"
      2 "Secondary or higher"
  /HC2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HC3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HC4     
   9998 "Flagged cases"
  /HC5     
   9998 "Flagged cases"
  /HC6     
   99998 "Flagged cases"
  /HC7     
   9998 "Flagged cases"
  /HC8     
   9998 "Flagged cases"
  /HC9     
   99998 "Flagged cases"
  /HC10    
   9998 "Flagged cases"
  /HC11    
   9998 "Flagged cases"
  /HC12    
   99998 "Flagged cases"
  /HC13    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HC15    
      0 "Not measured"
      1 "Lying"
      2 "Standing"
  /HC16    
     97 "Inconsistent"
     98 "Don't know"
  /HC27    
      1 "Male"
      2 "Female"
  /HC30    
     97 "Inconsistent"
     98 "Don't know"
  /HC31    
   9997 "Inconsistent"
   9998 "Don't know"
  /HC33    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HC51    
      0 "Not in household"
  /HC52    
      1 "Granted"
      2 "Refused"
  /HC53    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /HC55    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HC57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HC58    
      0 "No"
      1 "Yes"
  /HC60    
    993 "Mother not de facto"
    994 "Incomplete woman's interview"
    995 "Not in household"
  /HC61    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
  /HC68    
      0 "No education"
      1 "Primary"
      2 "Secondary or higher"
  /HC70    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HC71    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HC72    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HC73    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HB2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HB3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HB4     
   9998 "Flagged cases"
  /HB5     
   9998 "Flagged cases"
  /HB6     
   99998 "Flagged cases"
  /HB11    
   9998 "Flagged cases"
  /HB12    
   99998 "Flagged cases"
  /HB12A   
   99998 "Flagged cases"
  /HB12B   
   99998 "Flagged cases"
  /HB13    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HB33    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HB35    
      0 "Doesn't smoke"
     80 "80+"
     94 "Smokes pipes, cigars, etc"
  /HB40    
   9998 "Flagged cases"
  /HB41    
   9998 "Flagged cases"
  /HB50    
      1 "Under age 18"
      2 "Age 18 or older"
  /HB51    
      0 "Not in household"
  /HB52    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HB53    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /HB55    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HB57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HB58    
      0 "No"
      1 "Yes"
  /HB60    
      1 "Never in union"
      2 "Other"
  /HB61    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Sample not tested/lost/not enough DBS"
  /HB62    
   99993 "Sample damaged/insufficient/not found in lab"
   99994 "Not present"
   99995 "Refused"
   99996 "Other"
   '?    ' "Missing"
  /HB63    
      1 "Blood taken"
      2 "Not present"
      3 "Refused"
      4 "Sample not tested/lost/damaged/insufficient"
      5 "Not enough DBS to complete protocol"
      6 "Other"
  /HB64    
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
  /HB65    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /HB66    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /HB68    
      0 "No education"
      1 "Primary"
      2 "Secondary or higher"
  /HML3    
      0 "Not seen"
      1 "Yes, seen"
  /HML4    
     96 "More than 3 years ago"
     98 "Don't know"
  /HML5    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HML6    
      0 "Not pretreated"
      1 "Pretreated, permanent treatment"
      2 "Pretreated, requiring future treatment"
      3 "Not pretreated, came with kit and treated at home"
      4 "Pretreated, treatment type not known"
      6 "Other"
      8 "Don't know"
  /HML7    
     10 "Long-lasting insectiside treated nets (LLIN)"
     11 "Olyset"
     12 "Permanet"
     13 "Netprotect"
     16 "Other/DK brand (LLIN)"
     20 "Pretreated net"
     21 "Permethrin"
     22 "Deltamethrin"
     23 "Cyfluthrin"
     26 "Other/DK brand (pretreated)"
     96 "Other brand"
     98 "DK brand"
  /HML8    
      0 "No"
      1 "Yes"
      2 "Permanent net"
      8 "Not sure"
  /HML9    
     95 "25+ months ago"
     96 "More than 3 years ago"
     98 "Don't know"
  /HML10   
      0 "No, don't know"
      1 "Yes"
  /HML11   
      5 "5+"
  /HML21   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HMLA    
      0 "No one"
  /HML12   
      0 "Did not sleep under a net"
      1 "Only treated (ITN) nets"
      2 "Both treated (ITN) and untreated nets"
      3 "Only untreated nets"
  /HML13   
      0 "Did not sleep under net"
  /HML16   
     97 "97+"
     98 "Don't know"
  /HML17   
      0 "No data from Individual file"
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /HML18   
      0 "Not pregnant, don't know"
      1 "Pregnant"
  /HML19   
      0 "No"
      1 "Yes"
  /HML20   
      0 "No"
      1 "Yes"
  /HML30   
      0 "Not in household"
  /HML31   
      1 "Granted"
      2 "Refused"
  /HML32   
      0 "Negative"
      1 "Positive"
      6 "Test undetermined"
      7 "Sample not found in lab database"
  /HML32A  
      0 "No"
      1 "Yes"
  /HML32B  
      0 "No"
      1 "Yes"
  /HML32C  
      0 "No"
      1 "Yes"
  /HML32D  
      0 "No"
      1 "Yes"
  /HML32E  
      0 "No"
      1 "Yes"
  /HML32F  
      0 "No"
      1 "Yes"
  /HML32G  
      0 "No"
      1 "Yes"
  /HML33   
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
  /HML35   
      0 "Negative"
      1 "Positive"
  /CHL1    
      0 "No"
      1 "Yes, paid"
      2 "Yes, not paid"
  /CHL2    
     95 "95+"
     98 "Don't know"
  /CHL3    
      0 "No"
      1 "Yes"
  /CHL4    
     95 "95+"
     98 "Don't know"
  /CHL5    
      0 "No"
      1 "Yes"
  /CHL6    
     95 "95+"
     98 "Don't know"
  /CHL7    
      0 "No"
      1 "Yes"
  /CHL8    
     95 "95+"
     98 "Don't know"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\CI62\CIPR62FL.sav'.
