DATA LIST FILE='C:\COUNTRIES\CI62\CIMR62FL.DAT' RECORDS=1
  /
  MCASEID     1-15   (A)
  MV000      16-18   (A)
  MV001      19-26  
  MV002      27-30  
  MV003      31-33  
  MV004      34-37  
  MV005      38-45  
  MV006      46-47  
  MV007      48-51  
  MV008      52-55  
  MV009      56-57  
  MV010      58-61  
  MV011      62-65  
  MV012      66-67  
  MV013      68-69  
  MV014      70-70  
  MV015      71-71  
  MV016      72-73  
  MV021      74-77  
  MV022      78-81  
  MV023      82-83  
  MV024      84-85  
  MV025      86-86  
  MV026      87-87  
  MV027      88-88  
  MV028      89-91  
  MV029      92-93  
  MV030      94-96  
  MV031      97-99  
  MV032     100-101 
  MV034$1   102-103 
  MV034$2   104-105 
  MV034$3   106-107 
  MV034$4   108-109 
  MV034$5   110-111 
  MV034$6   112-113 
  MV034$7   114-115 
  MV034$8   116-117 
  MV034A$1  118-118 
  MV034A$2  119-119 
  MV034A$3  120-120 
  MV034A$4  121-121 
  MV034A$5  122-122 
  MV034A$6  123-123 
  MV034A$7  124-124 
  MV034A$8  125-125 
  MV034B$1  126-127 
  MV034B$2  128-129 
  MV034B$3  130-131 
  MV034B$4  132-133 
  MV034B$5  134-135 
  MV034B$6  136-137 
  MV034B$7  138-139 
  MV034B$8  140-141 
  MV035     142-142 
  MV801     143-146 
  MV802     147-150 
  MV803     151-152 
  MV101     153-154 
  MV102     155-155 
  MV103     156-156 
  MV104     157-158 
  MV105     159-159 
  MV106     160-160 
  MV107     161-162 
  MV130     163-164 
  MV131     165-167 
  MV133     168-169 
  MV134     170-170 
  MV135     171-171 
  MV136     172-173 
  MV138     174-175 
  MV149     176-176 
  MV150     177-178 
  MV151     179-179 
  MV152     180-181 
  MV155     182-182 
  MV156     183-183 
  MV157     184-184 
  MV158     185-185 
  MV159     186-186 
  MV167     187-188 
  MV168     189-189 
  MV190     190-190 
  MV191     191-198 
  MV201     199-200 
  MV202     201-202 
  MV203     203-204 
  MV204     205-206 
  MV205     207-208 
  MV206     209-210 
  MV207     211-212 
  MV212     213-214 
  MV213     215-215 
  MV217     216-216 
  MV218     217-218 
  MV225     219-219 
  MV245     220-221 
  MV246     222-222 
  MV247     223-224 
  MV248     225-225 
  MV249     226-226 
  MV250     227-227 
  MV251     228-229 
  MV252     230-230 
  MV301     231-231 
  MV302     232-232 
  M304A$01  233-233 
  M304A$02  234-234 
  M304A$03  235-235 
  M304A$04  236-236 
  M304A$05  237-237 
  M304A$06  238-238 
  M304A$07  239-239 
  M304A$08  240-240 
  M304A$09  241-241 
  M304A$10  242-242 
  M304A$11  243-243 
  M304A$12  244-244 
  M304A$13  245-245 
  M304A$14  246-246 
  M304A$15  247-247 
  M304A$16  248-248 
  M304A$17  249-249 
  M304A$18  250-250 
  M304A$19  251-251 
  M304A$20  252-252 
  MV304$01  253-253 
  MV304$02  254-254 
  MV304$03  255-255 
  MV304$04  256-256 
  MV304$05  257-257 
  MV304$06  258-258 
  MV304$07  259-259 
  MV304$08  260-260 
  MV304$09  261-261 
  MV304$10  262-262 
  MV304$11  263-263 
  MV304$12  264-264 
  MV304$13  265-265 
  MV304$14  266-266 
  MV304$15  267-267 
  MV304$16  268-268 
  MV304$17  269-269 
  MV304$18  270-270 
  MV304$19  271-271 
  MV304$20  272-272 
  MV305$01  273-273 
  MV305$02  274-274 
  MV305$03  275-275 
  MV305$04  276-276 
  MV305$05  277-277 
  MV305$06  278-278 
  MV305$07  279-279 
  MV305$08  280-280 
  MV305$09  281-281 
  MV305$10  282-282 
  MV305$11  283-283 
  MV305$12  284-284 
  MV305$13  285-285 
  MV305$14  286-286 
  MV305$15  287-287 
  MV305$16  288-288 
  MV305$17  289-289 
  MV305$18  290-290 
  MV305$19  291-291 
  MV305$20  292-292 
  MV307$01  293-293 
  MV307$02  294-294 
  MV307$03  295-295 
  MV307$04  296-296 
  MV307$05  297-297 
  MV307$06  298-298 
  MV307$07  299-299 
  MV307$08  300-300 
  MV307$09  301-301 
  MV307$10  302-302 
  MV307$11  303-303 
  MV307$12  304-304 
  MV307$13  305-305 
  MV307$14  306-306 
  MV307$15  307-307 
  MV307$16  308-308 
  MV307$17  309-309 
  MV307$18  310-310 
  MV307$19  311-311 
  MV307$20  312-312 
  MV312     313-314 
  MV313     315-315 
  MV323A    316-317 
  MV325B    318-324 
  MV372A    325-325 
  MV384A    326-326 
  MV384B    327-327 
  MV384C    328-328 
  MV395     329-329 
  MV396     330-330 
  MV3A09B   331-333 
  MV3B17    334-335 
  MV3B25A   336-336 
  MV3B25B   337-337 
  MV463A    338-338 
  MV463B    339-339 
  MV463C    340-340 
  MV463D    341-341 
  MV463E    342-342 
  MV463F    343-343 
  MV463G    344-344 
  MV463X    345-345 
  MV463Z    346-346 
  MV464     347-348 
  MV474     349-349 
  MV474A    350-350 
  MV474B    351-351 
  MV474C    352-352 
  MV474D    353-353 
  MV474E    354-354 
  MV474F    355-355 
  MV474G    356-356 
  MV474H    357-357 
  MV474I    358-358 
  MV474J    359-359 
  MV474X    360-360 
  MV474Z    361-361 
  MV475     362-362 
  MV476     363-363 
  MV477     364-365 
  MV478     366-367 
  MV479     368-369 
  MV480     370-370 
  MV481     371-371 
  MV481A    372-372 
  MV481B    373-373 
  MV481C    374-374 
  MV481D    375-375 
  MV481E    376-376 
  MV481F    377-377 
  MV481G    378-378 
  MV481H    379-379 
  MV481X    380-380 
  MV482A    381-381 
  MV482B    382-382 
  MV482C    383-383 
  MV483     384-384 
  MV483A    385-386 
  MV483B    387-388 
  MV483C    389-390 
  MV501     391-391 
  MV502     392-392 
  MV503     393-393 
  MV504     394-394 
  MV505     395-396 
  MV507     397-398 
  MV508     399-402 
  MV509     403-406 
  MV510     407-407 
  MV511     408-409 
  MV512     410-411 
  MV513     412-412 
  MV525     413-414 
  MV527     415-417 
  MV528     418-419 
  MV529     420-422 
  MV531     423-424 
  MV532     425-425 
  MV535     426-426 
  MV536     427-427 
  MV541     428-428 
  MV602     429-429 
  MV603     430-432 
  MV604     433-433 
  MV605     434-434 
  MV613     435-436 
  MV614     437-437 
  MV616     438-440 
  MV621     441-441 
  MV627     442-443 
  MV628     444-445 
  MV629     446-447 
  MV631     448-448 
  MV633A    449-449 
  MV633B    450-450 
  MV633C    451-451 
  MV633D    452-452 
  MV633E    453-453 
  MV633F    454-454 
  MV633G    455-455 
  MV634A    456-456 
  MV634B    457-457 
  MV634C    458-458 
  MV634D    459-459 
  MV714     460-460 
  MV714A    461-461 
  MV716     462-464 
  MV717     465-466 
  MV719     467-467 
  MV721     468-468 
  MV731     469-469 
  MV732     470-470 
  MV739     471-471 
  MV740     472-472 
  MV741     473-473 
  MV743A    474-474 
  MV743B    475-475 
  MV743C    476-476 
  MV743D    477-477 
  MV743E    478-478 
  MV743F    479-479 
  MV743G    480-480 
  MV744A    481-481 
  MV744B    482-482 
  MV744C    483-483 
  MV744D    484-484 
  MV744E    485-485 
  MV745A    486-486 
  MV745B    487-487 
  MV747A    488-488 
  MV747B    489-489 
  MV750     490-490 
  MV751     491-491 
  MV754BP   492-492 
  MV754CP   493-493 
  MV754DP   494-494 
  MV754JP   495-495 
  MV754WP   496-496 
  MV756     497-497 
  MV761     498-498 
  MV761B    499-499 
  MV761C    500-500 
  MV762AA   501-501 
  MV762AB   502-502 
  MV762AC   503-503 
  MV762AD   504-504 
  MV762AE   505-505 
  MV762AF   506-506 
  MV762AG   507-507 
  MV762AH   508-508 
  MV762AI   509-509 
  MV762AJ   510-510 
  MV762AK   511-511 
  MV762AL   512-512 
  MV762AM   513-513 
  MV762AN   514-514 
  MV762AO   515-515 
  MV762AP   516-516 
  MV762AQ   517-517 
  MV762AR   518-518 
  MV762AS   519-519 
  MV762AT   520-520 
  MV762AU   521-521 
  MV762AV   522-522 
  MV762AW   523-523 
  MV762AX   524-524 
  MV762AZ   525-525 
  MV762BA   526-526 
  MV762BB   527-527 
  MV762BC   528-528 
  MV762BD   529-529 
  MV762BE   530-530 
  MV762BF   531-531 
  MV762BG   532-532 
  MV762BH   533-533 
  MV762BI   534-534 
  MV762BJ   535-535 
  MV762BK   536-536 
  MV762BL   537-537 
  MV762BM   538-538 
  MV762BN   539-539 
  MV762BO   540-540 
  MV762BP   541-541 
  MV762BQ   542-542 
  MV762BR   543-543 
  MV762BS   544-544 
  MV762BT   545-545 
  MV762BU   546-546 
  MV762BV   547-547 
  MV762BW   548-548 
  MV762BX   549-549 
  MV762BZ   550-550 
  MV763A    551-551 
  MV763B    552-552 
  MV763C    553-553 
  MV763D    554-554 
  MV763E    555-555 
  MV763F    556-556 
  MV763G    557-557 
  MV766A    558-559 
  MV766B    560-561 
  MV767A    562-563 
  MV767B    564-565 
  MV767C    566-567 
  MV768A    568-570 
  MV768B    571-573 
  MV768C    574-576 
  MV769     577-577 
  MV769A    578-578 
  MV770     579-579 
  MV770A    580-580 
  MV770B    581-581 
  MV770C    582-582 
  MV770D    583-583 
  MV770E    584-584 
  MV770F    585-585 
  MV770G    586-586 
  MV770H    587-587 
  MV770I    588-588 
  MV770J    589-589 
  MV770K    590-590 
  MV770L    591-591 
  MV770M    592-592 
  MV770N    593-593 
  MV770O    594-594 
  MV770P    595-595 
  MV770Q    596-596 
  MV770R    597-597 
  MV770S    598-598 
  MV770T    599-599 
  MV770U    600-600 
  MV770V    601-601 
  MV770W    602-602 
  MV770X    603-603 
  MV774A    604-604 
  MV774B    605-605 
  MV774C    606-606 
  MV775     607-607 
  MV777     608-608 
  MV778     609-609 
  MV779     610-610 
  MV780     611-611 
  MV781     612-612 
  MV783     613-613 
  MV784A    614-614 
  MV784B    615-615 
  MV784C    616-616 
  MV784D    617-617 
  MV784E    618-618 
  MV784F    619-619 
  MV784G    620-620 
  MV784H    621-621 
  MV784I    622-622 
  MV784J    623-623 
  MV784K    624-624 
  MV784L    625-625 
  MV784M    626-626 
  MV784N    627-627 
  MV784O    628-628 
  MV784P    629-629 
  MV784Q    630-630 
  MV784R    631-631 
  MV784S    632-632 
  MV784T    633-633 
  MV784U    634-634 
  MV784V    635-635 
  MV784X    636-636 
  MV785     637-637 
  MV791     638-638 
  MV793     639-639 
  MV793A    640-640 
  MV793B    641-641 
  MV820     642-642 
  MV822     643-643 
  MV823     644-644 
  MV824     645-645 
  MV825     646-646 
  MV826     647-647 
  MV826A    648-649 
  MV827     650-650 
  MV828     651-651 
  MV829     652-653 
  MV832B    654-656 
  MV832C    657-659 
  MV833A    660-660 
  MV833B    661-661 
  MV833C    662-662 
  MV834A    663-664 
  MV834B    665-666 
  MV834C    667-668 
  MV835A    669-669 
  MV835B    670-670 
  MV835C    671-671 
  MV836     672-673 
  MV837     674-674 
  MV844     675-675 
  MV845     676-676 
  MV846     677-677 
  MV847     678-678 
  MV848     679-679 
  MV849     680-680 
  MV851A    681-681 
  MV851B    682-682 
  MV851C    683-683 
  MV851D    684-684 
  MV851E    685-685 
  MV851F    686-686 
  MV851G    687-687 
  MV851H    688-688 
  MV851I    689-689 
  MV851J    690-690 
  MV851K    691-691 
  MV851L    692-692 
  MV852A    693-695 
  MV852B    696-698 
  MV852C    699-701 
  MV853A    702-703 
  MV853B    704-705 
  MV853C    706-707 
  MV854A    708-708 
  MV854B    709-709 
  MG100     710-710 
  MG101     711-711 
  MG117A    712-712 
  MG117B    713-713 
  MG117C    714-714 
  MG117D    715-715 
  MG117E    716-716 
  MG117F    717-717 
  MG117G    718-718 
  MG117H    719-719 
  MG117I    720-720 
  MG117J    721-721 
  MG117X    722-722 
  MG117Y    723-723 
  MG118     724-724 
  MG119     725-725 
  SM302D    726-726 
  SM302B1   727-727 
  SM302B2   728-728 
  SM302B3   729-729 
  SM302B4   730-730 
  SM302C1   731-731 
  SM302E1   732-732 
  SM302E2   733-733 
  SM302E3   734-734 
  SM302E4   735-735 
  SM302G1   736-736 
  SM302G2   737-737 
  SM302G3   738-738 
  SM302G4   739-739 
  SM402A    740-740 
  SM707A    741-741 
  SM707B    742-742 
  SM707C    743-743 
  SM707D    744-744 
 .
VARIABLE LABELS
   MCASEID  "Case Identification"
  /MV000    "Country code and phase"
  /MV001    "Cluster number"
  /MV002    "Household number"
  /MV003    "Respondent's line number"
  /MV004    "Ultimate area unit"
  /MV005    "Men's sample weight (6 decimals)"
  /MV006    "Month of interview"
  /MV007    "Year of interview"
  /MV008    "Date of interview (CMC)"
  /MV009    "Month of birth"
  /MV010    "Year of birth"
  /MV011    "Date of birth (CMC)"
  /MV012    "Current age"
  /MV013    "Age in 5-year groups"
  /MV014    "Completeness of age information"
  /MV015    "Result of interview"
  /MV016    "Day of interview"
  /MV021    "Primary sampling unit"
  /MV022    "Sample stratum number"
  /MV023    "Sample domain"
  /MV024    "Region"
  /MV025    "Type of place of residence"
  /MV026    "De facto place of residence"
  /MV027    "Number of visits"
  /MV028    "Interviewer identification"
  /MV029    "Keyer identification"
  /MV030    "Field supervisor"
  /MV031    "Field editor"
  /MV032    "Office editor"
  /MV034$1  "Line number of wife/partner"
  /MV034$2  "Line number of wife/partner"
  /MV034$3  "Line number of wife/partner"
  /MV034$4  "Line number of wife/partner"
  /MV034$5  "Line number of wife/partner"
  /MV034$6  "Line number of wife/partner"
  /MV034$7  "Line number of wife/partner"
  /MV034$8  "Line number of wife/partner"
  /MV034A$1 "NA - Wife or partner***"
  /MV034A$2 "NA - Wife or partner***"
  /MV034A$3 "NA - Wife or partner***"
  /MV034A$4 "NA - Wife or partner***"
  /MV034A$5 "NA - Wife or partner***"
  /MV034A$6 "NA - Wife or partner***"
  /MV034A$7 "NA - Wife or partner***"
  /MV034A$8 "NA - Wife or partner***"
  /MV034B$1 "Age of wife/partner"
  /MV034B$2 "Age of wife/partner"
  /MV034B$3 "Age of wife/partner"
  /MV034B$4 "Age of wife/partner"
  /MV034B$5 "Age of wife/partner"
  /MV034B$6 "Age of wife/partner"
  /MV034B$7 "Age of wife/partner"
  /MV034B$8 "Age of wife/partner"
  /MV035    "Number of wives/partners"
  /MV801    "Time interview started (hhmm - 24 hour clock)"
  /MV802    "Time interview ended (hhmm - 24 hour clock)"
  /MV803    "Length of interview in minutes"
  /MV101    "Region"
  /MV102    "Type of place of residence"
  /MV103    "NA - Childhood place of residence***"
  /MV104    "NA - Years lived in place of residence"
  /MV105    "NA - Type of place of previous residence"
  /MV106    "Educational level"
  /MV107    "Highest year of education (at level in MV106)"
  /MV130    "Religion"
  /MV131    "Ethnicity"
  /MV133    "Total number of years of education"
  /MV134    "De facto place of residence"
  /MV135    "Usual resident or visitor"
  /MV136    "Number of household members (total listed)"
  /MV138    "Number of eligible men in household (de facto)"
  /MV149    "Educational attainment"
  /MV150    "Relationship to household head"
  /MV151    "Sex of household head"
  /MV152    "Age of household head"
  /MV155    "Literacy"
  /MV156    "NA - Ever participated in a literacy program (excluding primary school)"
  /MV157    "Frequency of reading newspaper or magazine"
  /MV158    "Frequency of listening to radio"
  /MV159    "Frequency of watching television"
  /MV167    "Times away from home in last 12 months"
  /MV168    "Away for more than one month in last 12 months"
  /MV190    "Wealth index"
  /MV191    "Wealth index factor score (5 decimals)"
  /MV201    "Total children ever born"
  /MV202    "Sons at home"
  /MV203    "Daughters at home"
  /MV204    "Sons elsewhere"
  /MV205    "Daughters elsewhere"
  /MV206    "Sons who have died"
  /MV207    "Daughters who have died"
  /MV212    "Age of respondent at 1st birth"
  /MV213    "Partner currently pregnant"
  /MV217    "Knowledge of ovulatory cycle"
  /MV218    "Number of living children"
  /MV225    "NA - Most recent pregnancy wanted***"
  /MV245    "Number of women fathered children with"
  /MV246    "NA - Married to mother when first child was born***"
  /MV247    "Age of most recent child"
  /MV248    "Antenatal check-ups for the mother of most recent child"
  /MV249    "Respondent present during check-ups for most recent child"
  /MV250    "Place of birth of most recent child"
  /MV251    "NA - Reason for not delivering most recent child in health facility"
  /MV252    "Amount a child should drink, when that child has diarrhea"
  /MV301    "Knowledge of any contraceptive method"
  /MV302    "NA - Ever use of any contraceptive method"
  /M304A$01 "Type of contraceptive method"
  /M304A$02 "Type of contraceptive method"
  /M304A$03 "Type of contraceptive method"
  /M304A$04 "Type of contraceptive method"
  /M304A$05 "Type of contraceptive method"
  /M304A$06 "Type of contraceptive method"
  /M304A$07 "Type of contraceptive method"
  /M304A$08 "Type of contraceptive method"
  /M304A$09 "Type of contraceptive method"
  /M304A$10 "Type of contraceptive method"
  /M304A$11 "Type of contraceptive method"
  /M304A$12 "Type of contraceptive method"
  /M304A$13 "Type of contraceptive method"
  /M304A$14 "Type of contraceptive method"
  /M304A$15 "Type of contraceptive method"
  /M304A$16 "Type of contraceptive method"
  /M304A$17 "Type of contraceptive method"
  /M304A$18 "Type of contraceptive method"
  /M304A$19 "Type of contraceptive method"
  /M304A$20 "Type of contraceptive method"
  /MV304$01 "Knows contraceptive method"
  /MV304$02 "Knows contraceptive method"
  /MV304$03 "Knows contraceptive method"
  /MV304$04 "Knows contraceptive method"
  /MV304$05 "Knows contraceptive method"
  /MV304$06 "Knows contraceptive method"
  /MV304$07 "Knows contraceptive method"
  /MV304$08 "Knows contraceptive method"
  /MV304$09 "Knows contraceptive method"
  /MV304$10 "Knows contraceptive method"
  /MV304$11 "Knows contraceptive method"
  /MV304$12 "Knows contraceptive method"
  /MV304$13 "Knows contraceptive method"
  /MV304$14 "Knows contraceptive method"
  /MV304$15 "Knows contraceptive method"
  /MV304$16 "Knows contraceptive method"
  /MV304$17 "Knows contraceptive method"
  /MV304$18 "Knows contraceptive method"
  /MV304$19 "Knows contraceptive method"
  /MV304$20 "Knows contraceptive method"
  /MV305$01 "NA - Ever used contraceptive method"
  /MV305$02 "NA - Ever used contraceptive method"
  /MV305$03 "NA - Ever used contraceptive method"
  /MV305$04 "NA - Ever used contraceptive method"
  /MV305$05 "NA - Ever used contraceptive method"
  /MV305$06 "NA - Ever used contraceptive method"
  /MV305$07 "NA - Ever used contraceptive method"
  /MV305$08 "NA - Ever used contraceptive method"
  /MV305$09 "NA - Ever used contraceptive method"
  /MV305$10 "NA - Ever used contraceptive method"
  /MV305$11 "NA - Ever used contraceptive method"
  /MV305$12 "NA - Ever used contraceptive method"
  /MV305$13 "NA - Ever used contraceptive method"
  /MV305$14 "NA - Ever used contraceptive method"
  /MV305$15 "NA - Ever used contraceptive method"
  /MV305$16 "NA - Ever used contraceptive method"
  /MV305$17 "NA - Ever used contraceptive method"
  /MV305$18 "NA - Ever used contraceptive method"
  /MV305$19 "NA - Ever used contraceptive method"
  /MV305$20 "NA - Ever used contraceptive method"
  /MV307$01 "Contraceptive method currently used"
  /MV307$02 "Contraceptive method currently used"
  /MV307$03 "Contraceptive method currently used"
  /MV307$04 "Contraceptive method currently used"
  /MV307$05 "Contraceptive method currently used"
  /MV307$06 "Contraceptive method currently used"
  /MV307$07 "Contraceptive method currently used"
  /MV307$08 "Contraceptive method currently used"
  /MV307$09 "Contraceptive method currently used"
  /MV307$10 "Contraceptive method currently used"
  /MV307$11 "Contraceptive method currently used"
  /MV307$12 "Contraceptive method currently used"
  /MV307$13 "Contraceptive method currently used"
  /MV307$14 "Contraceptive method currently used"
  /MV307$15 "Contraceptive method currently used"
  /MV307$16 "Contraceptive method currently used"
  /MV307$17 "Contraceptive method currently used"
  /MV307$18 "Contraceptive method currently used"
  /MV307$19 "Contraceptive method currently used"
  /MV307$20 "Contraceptive method currently used"
  /MV312    "Current contraceptive method"
  /MV313    "Current contraceptive by method type"
  /MV323A   "Brand of condom used"
  /MV325B   "NA - Cost of condoms (in CURRENCY) last time obtained"
  /MV372A   "NA - Interviewer shown condom package"
  /MV384A   "On radio heard about Family Planning in the last few months"
  /MV384B   "On TV saw about Family Planning in the last few months"
  /MV384C   "In newspaper read about Family Planning in the last few months"
  /MV395    "Discussed Family Planning with health worker in last few months"
  /MV396    "NA - Possible for a breastfeeding woman to get pregnant"
  /MV3A09B  "NA - Number of condoms did get last time"
  /MV3B17   "Source of condoms"
  /MV3B25A  "Contraception is woman's business, man should not worry"
  /MV3B25B  "Women who use contraception become promiscuous"
  /MV463A   "Smokes cigarettes"
  /MV463B   "Smokes pipe"
  /MV463C   "Uses chewing tobacco"
  /MV463D   "Uses snuff"
  /MV463E   "NA - Smokes CS"
  /MV463F   "NA - Smokes CS"
  /MV463G   "NA - Smokes CS"
  /MV463X   "Smokes other"
  /MV463Z   "Smokes nothing"
  /MV464    "Number of cigarettes in last 24 hours"
  /MV474    "NA - Heard of tuberculosis or TB"
  /MV474A   "NA - Tuberculosis spread by: air through coughing or sneezing"
  /MV474B   "NA - Tuberculosis spread by: sharing utensils"
  /MV474C   "NA - Tuberculosis spread by: touching a person with TB"
  /MV474D   "NA - Tuberculosis spread by: food"
  /MV474E   "NA - Tuberculosis spread by: sexual contact"
  /MV474F   "NA - Tuberculosis spread by: mosquito bites"
  /MV474G   "NA - Tuberculosis spread by: CS"
  /MV474H   "NA - Tuberculosis spread by: CS"
  /MV474I   "NA - Tuberculosis spread by: CS"
  /MV474J   "NA - Tuberculosis spread by: CS"
  /MV474X   "NA - Tuberculosis spread by: other"
  /MV474Z   "NA - Don't know how tuberculosis is spread"
  /MV475    "NA - Tuberculosis can be cured"
  /MV476    "NA - Would want tuberculosis infection in family to remain secret"
  /MV477    "Number of injections in last 12 months"
  /MV478    "Number of injections administered by a health worker"
  /MV479    "NA - Place where given injection by health worker"
  /MV480    "Syringe and needle from new, unopened package"
  /MV481    "Covered by health insurance"
  /MV481A   "Health insurance type: mutual/community organization"
  /MV481B   "Health insurance type: provided by employer"
  /MV481C   "Health insurance type: social security"
  /MV481D   "Health insurance type: private/commercially purchased"
  /MV481E   "NA - Health insurance type: CS"
  /MV481F   "NA - Health insurance type: CS"
  /MV481G   "NA - Health insurance type: CS"
  /MV481H   "NA - Health insurance type: CS"
  /MV481X   "Health insurance type: other"
  /MV482A   "NA - Arrange care of biological children under age 18***"
  /MV482B   "NA - Primary caregiver of children under age 18***"
  /MV482C   "NA - Arrange care of non-biological children < 18***"
  /MV483    "Respondent circumcised"
  /MV483A   "Age at circumcision"
  /MV483B   "Who performed the circumcision"
  /MV483C   "Place where circumcision was done"
  /MV501    "Current marital status"
  /MV502    "Currently/formerly/never in union"
  /MV503    "Number of unions"
  /MV504    "Currently residing with wife/partner"
  /MV505    "Number of wives/partners"
  /MV507    "Month of first cohabitation"
  /MV508    "Year of first cohabitation"
  /MV509    "Date of first cohabitation (CMC)"
  /MV510    "Completeness of date information in MV509"
  /MV511    "Age at first cohabitation"
  /MV512    "Years since first cohabitation"
  /MV513    "Cohabitation duration (grouped)"
  /MV525    "Age at first sex"
  /MV527    "Time since last sex"
  /MV528    "Time since last sex (in days)"
  /MV529    "Time since last sex (in months)"
  /MV531    "Age at first sex (imputed)"
  /MV532    "Flag for MV531"
  /MV535    "Ever been married or in union"
  /MV536    "Recent sexual activity"
  /MV541    "NA - Intends to wait until marriage to have sex"
  /MV602    "Fertility preference"
  /MV603    "Preferred waiting time for birth of a/another child"
  /MV604    "Preferred waiting time for birth of a/another child (grouped)"
  /MV605    "Desire for more children"
  /MV613    "Ideal number of children"
  /MV614    "Ideal number of children (grouped)"
  /MV616    "Desired time for future birth"
  /MV621    "NA - Wife's desire for children***"
  /MV627    "Ideal number of boys"
  /MV628    "Ideal number of girls"
  /MV629    "Ideal number of either sex"
  /MV631    "NA - Problem if wife became pregnant***"
  /MV633A   "NA - Wife justified refusing sex: husband has STI"
  /MV633B   "Wife justified refusing sex: husband has other women"
  /MV633C   "NA - Wife justified refusing sex: recent birth"
  /MV633D   "NA - Wife justified refusing sex: tired, not in mood"
  /MV633E   "NA - Wife justified refusing sex: CS reason"
  /MV633F   "NA - Wife justified refusing sex: CS reason"
  /MV633G   "NA - Wife justified refusing sex: CS reason"
  /MV634A   "NA - Wife refuses to have sex, husband has right to: get angry"
  /MV634B   "NA - Wife refuses to have sex, husband has right to: refuse financial support"
  /MV634C   "NA - Wife refuses to have sex, husband has right to: use force for sex"
  /MV634D   "NA - Wife refuses to have sex, husband has right to: have sex with another women"
  /MV714    "Currently working"
  /MV714A   "Have a job, but currently absent"
  /MV716    "Occupation"
  /MV717    "Occupation (grouped)"
  /MV719    "NA - Works for family, others, self"
  /MV721    "NA - Works at home or away"
  /MV731    "Worked in last 12 months"
  /MV732    "Employment all year/seasonal"
  /MV739    "Person who usually decides how to spend respondent's earnings"
  /MV740    "NA - Type of land where respondent works"
  /MV741    "Type of earnings from respondent's work"
  /MV743A   "Person who should have greater say: respondent's health care"
  /MV743B   "Person who should have greater say: large household purchases"
  /MV743C   "NA - Person who should have greater say: daily household purchases"
  /MV743D   "NA - Person who should have greater say: visits to family or relatives"
  /MV743E   "NA - Person who should have greater say: food to be cooked each day"
  /MV743F   "NA - Person who should have greater say: deciding what to do with money wife earns"
  /MV743G   "NA - Person who should have greater say: deciding how many children to have"
  /MV744A   "Beating justified: wife goes out without telling husband"
  /MV744B   "Beating justified: wife neglects the children"
  /MV744C   "Beating justified: wife argues with husband"
  /MV744D   "Beating justified: wife refuses to have sex with husband"
  /MV744E   "Beating justified: wife burns food"
  /MV745A   "Owns a house alone or jointly"
  /MV745B   "Owns land alone or jointly"
  /MV747A   "NA - Childbearing is a woman's concern"
  /MV747B   "NA - Important for mother/child health to get assistance at delivery"
  /MV750    "Ever heard of a Sexually Transmitted Infection (STI)"
  /MV751    "Ever heard of AIDS"
  /MV754BP  "NA - Reduce risk of getting HIV: do not have sex at all"
  /MV754CP  "Reduce risk of getting HIV: always use condoms during sex"
  /MV754DP  "Reduce risk of getting HIV: have 1 sex partner only, who has no other partners"
  /MV754JP  "Can get HIV from mosquito bites"
  /MV754WP  "Can get HIV by sharing food with person who has AIDS"
  /MV756    "A healthy looking person can have HIV"
  /MV761    "Condom used during last sex with most recent partner"
  /MV761B   "Condom used during last sex with 2nd to most recent partner"
  /MV761C   "Condom used during last sex with 3rd to most recent partner"
  /MV762AA  "Source for condoms: government hospital"
  /MV762AB  "Source for condoms: government health center"
  /MV762AC  "Source for condoms: family planning clinic"
  /MV762AD  "Source for condoms: mobile clinic"
  /MV762AE  "Source for condoms: field worker"
  /MV762AF  "Source for condoms: other public"
  /MV762AG  "NA - Source for condoms: CS public"
  /MV762AH  "NA - Source for condoms: CS public"
  /MV762AI  "NA - Source for condoms: CS public"
  /MV762AJ  "Source for condoms: private hospital/clinic"
  /MV762AK  "Source for condoms: pharmacy"
  /MV762AL  "Source for condoms: private doctor"
  /MV762AM  "Source for condoms: private mobile clinic"
  /MV762AN  "Source for condoms: private field worker"
  /MV762AO  "Source for condoms: other private medical sector"
  /MV762AP  "NA - Source for condoms: CS private"
  /MV762AQ  "NA - Source for condoms: CS private"
  /MV762AR  "NA - Source for condoms: CS private"
  /MV762AS  "Source for condoms: shop"
  /MV762AT  "Source for condoms: church"
  /MV762AU  "Source for condoms: friends/relatives"
  /MV762AV  "NA - Source for condoms: CS other"
  /MV762AW  "NA - Source for condoms: CS other"
  /MV762AX  "Source for condoms: other"
  /MV762AZ  "Don't know any source for condoms"
  /MV762BA  "Source for female condoms: government hospital"
  /MV762BB  "Source for female condoms: government health center"
  /MV762BC  "Source for female condoms: family planning clinic"
  /MV762BD  "Source for female condoms: mobile clinic"
  /MV762BE  "Source for female condoms: field worker"
  /MV762BF  "Source for female condoms: other public"
  /MV762BG  "NA - Source for female condoms: CS public"
  /MV762BH  "NA - Source for female condoms: CS public"
  /MV762BI  "NA - Source for female condoms: CS public"
  /MV762BJ  "Source for female condoms: private hospital/clinic"
  /MV762BK  "Source for female condoms: pharmacy"
  /MV762BL  "Source for female condoms: private doctor"
  /MV762BM  "Source for female condoms: private mobile clinic"
  /MV762BN  "Source for female condoms: private field worker"
  /MV762BO  "Source for female condoms: other private medical"
  /MV762BP  "NA - Source for female condoms: CS private"
  /MV762BQ  "NA - Source for female condoms: CS private"
  /MV762BR  "NA - Source for female condoms: CS private"
  /MV762BS  "Source for female condoms: shop"
  /MV762BT  "Source for female condoms: church"
  /MV762BU  "Source for female condoms: friends/relatives"
  /MV762BV  "NA - Source for female condoms: CS other"
  /MV762BW  "NA - Source for female condoms: CS other"
  /MV762BX  "Source for female condoms: other"
  /MV762BZ  "Don't know any source for female condoms"
  /MV763A   "Had any STI in last 12 months"
  /MV763B   "Had genital sore/ulcer in last 12 months"
  /MV763C   "Had genital discharge in last 12 months"
  /MV763D   "NA - Had CS STI in last 12 months"
  /MV763E   "NA - Had CS STI in last 12 months"
  /MV763F   "NA - Had CS STI in last 12 months"
  /MV763G   "NA - Had CS STI in last 12 months"
  /MV766A   "Number of sex partners, excluding spouse, in last 12 months"
  /MV766B   "Number of sex partners, including spouse, in last 12 months"
  /MV767A   "Relationship with most recent sex partner"
  /MV767B   "Relationship with 2nd to most recent sex partner"
  /MV767C   "Relationship with 3rd to most recent sex partner"
  /MV768A   "NA - Length of time had sex relations with most recent partner"
  /MV768B   "NA - Length of time had sex relations with 2nd to most recent partner"
  /MV768C   "NA - Length of time had sex relations with 3rd to most recent partner"
  /MV769    "Can get a condom"
  /MV769A   "Can get a female condom"
  /MV770    "Sought advice/treatment for last STI infection"
  /MV770A   "Sought STI advice/treatment from: government hospital"
  /MV770B   "Sought STI advice/treatment from: government health center"
  /MV770C   "Sought STI advice/treatment from: public stand-alone VCT center"
  /MV770D   "Sought STI advice/treatment from: family planning clinic"
  /MV770E   "Sought STI advice/treatment from: mobile clinic"
  /MV770F   "Sought STI advice/treatment from: field worker"
  /MV770G   "Sought STI advice/treatment from: other public"
  /MV770H   "NA - Sought STI advice/treatment from: CS public"
  /MV770I   "NA - Sought STI advice/treatment from: CS public"
  /MV770J   "NA - Sought STI advice/treatment from: CS public"
  /MV770K   "Sought STI advice/treatment from: private hospital/clinic/doctor"
  /MV770L   "Sought STI advice/treatment from: private stand-alone VCT center"
  /MV770M   "Sought STI advice/treatment from: pharmacy"
  /MV770N   "Sought STI advice/treatment from: private mobile clinic"
  /MV770O   "Sought STI advice/treatment from: private field worker"
  /MV770P   "Sought STI advice/treatment from: other private medical"
  /MV770Q   "NA - Sought STI advice/treatment from: CS private"
  /MV770R   "NA - Sought STI advice/treatment from: CS private"
  /MV770S   "NA - Sought STI advice/treatment from: CS private"
  /MV770T   "Sought STI advice/treatment from: shop"
  /MV770U   "NA - Sought STI advice/treatment from: CS other"
  /MV770V   "NA - Sought STI advice/treatment from: CS other"
  /MV770W   "NA - Sought STI advice/treatment from: CS other"
  /MV770X   "Sought STI advice/treatment from: other"
  /MV774A   "HIV transmitted during pregnancy"
  /MV774B   "HIV transmitted during delivery"
  /MV774C   "HIV transmitted by breastfeeding"
  /MV775    "NA - Knows someone who has, or is suspected of having, HIV"
  /MV777    "Would want HIV infection in family to remain secret"
  /MV778    "Willing to care for relative with AIDS"
  /MV779    "A female teacher infected with HIV, but is not sick, should be allowed to continue teaching"
  /MV780    "Children should be taught about condoms to avoid AIDS"
  /MV781    "Ever been tested for HIV"
  /MV783    "Know a place to get HIV test"
  /MV784A   "Place for HIV test: government hospital"
  /MV784B   "Place for HIV test: government health center"
  /MV784C   "Place for HIV test: public standalone VCT center"
  /MV784D   "Place for HIV test: family planning clinic"
  /MV784E   "Place for HIV test: mobile clinic"
  /MV784F   "Place for HIV test: field worker"
  /MV784G   "Place for HIV test: other public"
  /MV784H   "NA - Place for HIV test: CS public"
  /MV784I   "NA - Place for HIV test: CS public"
  /MV784J   "NA - Place for HIV test: CS public"
  /MV784K   "Place for HIV test: private hospital/clinic/doctor"
  /MV784L   "Place for HIV test: private standalone VCT center"
  /MV784M   "Place for HIV test: pharmacy"
  /MV784N   "Place for HIV test: private mobile clinic"
  /MV784O   "Place for HIV test: private field worker"
  /MV784P   "Place for HIV test: other private medical"
  /MV784Q   "NA - Place for HIV test: CS private"
  /MV784R   "NA - Place for HIV test: CS private"
  /MV784S   "NA - Place for HIV test: CS other"
  /MV784T   "NA - Place for HIV test: CS other"
  /MV784U   "NA - Place for HIV test: CS other"
  /MV784V   "NA - Place for HIV test: CS other"
  /MV784X   "Place for HIV test: other"
  /MV785    "Heard about other STIs"
  /MV791    "Have ever paid anyone in exchange for sex"
  /MV793    "Paid for sex in last 12 months"
  /MV793A   "Condom used last time paid for sex in last 12 months"
  /MV793B   "Condom used every time paid for sex in last 12 months"
  /MV820    "NA - Condom used at first sex"
  /MV822    "Wife justified asking husband to use condom if he has STI"
  /MV823    "Can get HIV by witchcraft or supernatural means"
  /MV824    "Drugs to avoid HIV transmission to baby during pregnancy"
  /MV825    "Would buy vegetables from vendor with HIV"
  /MV826    "NA - Last time tested for HIV"
  /MV826A   "Months ago most recent HIV test"
  /MV827    "NA - Last HIV test: on your own, offered or required"
  /MV828    "Received result from last HIV test"
  /MV829    "Place where last HIV test was taken"
  /MV832B   "Time since last sex with 2nd to most recent partner"
  /MV832C   "Time since last sex with 3rd to most recent partner"
  /MV833A   "Used condom every time had sex with most recent partner in last 12 months"
  /MV833B   "Used condom every time had sex with 2nd to most recent partner in last 12 months"
  /MV833C   "Used condom every time had sex with 3rd to most recent partner in last 12 months"
  /MV834A   "Age of most recent partner"
  /MV834B   "Age of 2nd to most recent partner"
  /MV834C   "Age of 3rd to most recent partner"
  /MV835A   "NA - Alcohol consumption at last sex with most recent partner"
  /MV835B   "NA - Alcohol consumption at last sex with 2nd to most recent partner"
  /MV835C   "NA - Alcohol consumption at last sex with 3rd to most recent partner"
  /MV836    "Total lifetime number of sex partners"
  /MV837    "NA - Heard of drugs to help HIV infected people live longer"
  /MV844    "NA - Knows someone denied health services for having, or suspected of having, HIV; in last 12 months"
  /MV845    "NA - Knows someone denied social event for having, or suspected of having, HIV; in last 12 months"
  /MV846    "NA - Knows someone verbally abused for having, or suspected of having, HIV; in last 12 months"
  /MV847    "NA - People with HIV should be ashamed of themselves"
  /MV848    "NA - People with HIV should be blamed for bringing disease to community"
  /MV849    "NA - Children 12-14 should be taught to wait for sex until marriage"
  /MV851A   "NA - Young men should wait for sex until marriage"
  /MV851B   "NA - Most young men wait for sex until marriage"
  /MV851C   "NA - Unmarried sexually active men should have only one partner"
  /MV851D   "NA - Most unmarried sexually active men have only one partner"
  /MV851E   "NA - Married men should only have sex with their wives"
  /MV851F   "NA - Most married men only have sex with their wives"
  /MV851G   "NA - Young women should wait for sex until marriage"
  /MV851H   "NA - Most young women wait for sex until marriage"
  /MV851I   "NA - Unmarried sexually active women should have only one partner"
  /MV851J   "NA - Most unmarried sexually active women have only one partner"
  /MV851K   "NA - Married women should only have sex with their husbands"
  /MV851L   "NA - Most married women only have sex with their husbands"
  /MV852A   "How long ago first had sex with most recent partner"
  /MV852B   "How long ago first had sex with 2nd most recent partner"
  /MV852C   "How long ago first had sex with 3rd most recent partner"
  /MV853A   "Times in last 12 months had sex with most recent partner"
  /MV853B   "Times in last 12 months had sex with 2nd most recent partner"
  /MV853C   "Times in last 12 months had sex with 3rd most recent partner"
  /MV854A   "NA - Concurrent sexual partners"
  /MV854B   "NA - Cumulative concurrent sexual partners"
  /MG100    "Ever heard of female circumcision"
  /MG101    "Ever heard of genital cutting (probed)"
  /MG117A   "NA - Female circumcision benefit: cleanliness/hygiene"
  /MG117B   "NA - Female circumcision benefit: social acceptance"
  /MG117C   "NA - Female circumcision benefit: better marriage prospects"
  /MG117D   "NA - Female circumcision benefit: virginity/prevent premarital sex"
  /MG117E   "NA - Female circumcision benefit: greater sexual pleasure for men"
  /MG117F   "NA - Female circumcision benefit: religious approval"
  /MG117G   "NA - Female circumcision benefit: CS"
  /MG117H   "NA - Female circumcision benefit: CS"
  /MG117I   "NA - Female circumcision benefit: CS"
  /MG117J   "NA - Female circumcision benefit: CS"
  /MG117X   "NA - Female circumcision benefit: other"
  /MG117Y   "NA - No benefit from female circumcision"
  /MG118    "Female circumcision required by religion"
  /MG119    "Female circumcision: continue or be stopped"
  /SM302D   "Heard about family planning on a poster or leaflet"
  /SM302B1  "Heard about family planning on the radio: RCI / Fréquence 2"
  /SM302B2  "Heard about family planning on the radio: ONUCI-FM"
  /SM302B3  "Heard about family planning on the radio: Commercial radio"
  /SM302B4  "Heard about family planning on the radio: Religious radio"
  /SM302C1  "Heard about family planning on local radio: Espace Santé"
  /SM302E1  "Heard about family planning on TV: RTI"
  /SM302E2  "Heard about family planning on TV: European channel"
  /SM302E3  "Heard about family planning on TV: African channel"
  /SM302E4  "Heard about family planning on TV: Other channel"
  /SM302G1  "Heard message about existence of family planning services"
  /SM302G2  "Heard message about places to get contraceptives"
  /SM302G3  "Heard message about types of contraceptive methods"
  /SM302G4  "Heard message about health/economic benefits of family planning"
  /SM402A   "Respondent consented to marriage"
  /SM707A   "AIDS virus transmitted by sharp objects"
  /SM707B   "AIDS virus transmitted by injections"
  /SM707C   "AIDS virus transmitted by blood transfusion"
  /SM707D   "AIDS virus transmitted by toothbrush"
 .
MISSING VALUE
   MV015    (9)
  /MV026    (9)
  /MV027    (9)
  /MV028    (999)
  /MV029    (99)
  /MV030    (999)
  /MV031    (999)
  /MV032    (99)
  /MV034$1  (99)
  /MV034$2  (99)
  /MV034$3  (99)
  /MV034$4  (99)
  /MV034$5  (99)
  /MV034$6  (99)
  /MV034$7  (99)
  /MV034$8  (99)
  /MV034A$1 (9)
  /MV034A$2 (9)
  /MV034A$3 (9)
  /MV034A$4 (9)
  /MV034A$5 (9)
  /MV034A$6 (9)
  /MV034A$7 (9)
  /MV034A$8 (9)
  /MV034B$1 (99)
  /MV034B$2 (99)
  /MV034B$3 (99)
  /MV034B$4 (99)
  /MV034B$5 (99)
  /MV034B$6 (99)
  /MV034B$7 (99)
  /MV034B$8 (99)
  /MV035    (9)
  /MV801    (9999)
  /MV802    (9999)
  /MV803    (99)
  /MV103    (9)
  /MV104    (99)
  /MV105    (9)
  /MV106    (9)
  /MV107    (99)
  /MV130    (99)
  /MV131    (999)
  /MV133    (99)
  /MV134    (9)
  /MV135    (9)
  /MV149    (9)
  /MV150    (99)
  /MV152    (99)
  /MV155    (9)
  /MV156    (9)
  /MV157    (9)
  /MV158    (9)
  /MV159    (9)
  /MV167    (99)
  /MV168    (9)
  /MV201    (99)
  /MV203    (99)
  /MV212    (99)
  /MV213    (9)
  /MV217    (9)
  /MV218    (99)
  /MV225    (9)
  /MV245    (99)
  /MV246    (9)
  /MV247    (99)
  /MV248    (9)
  /MV249    (9)
  /MV250    (9)
  /MV251    (99)
  /MV252    (9)
  /MV304$01 (9)
  /MV304$02 (9)
  /MV304$03 (9)
  /MV304$04 (9)
  /MV304$05 (9)
  /MV304$06 (9)
  /MV304$07 (9)
  /MV304$08 (9)
  /MV304$09 (9)
  /MV304$10 (9)
  /MV304$11 (9)
  /MV304$12 (9)
  /MV304$13 (9)
  /MV304$14 (9)
  /MV304$15 (9)
  /MV304$16 (9)
  /MV304$17 (9)
  /MV304$18 (9)
  /MV304$19 (9)
  /MV304$20 (9)
  /MV305$01 (9)
  /MV305$02 (9)
  /MV305$03 (9)
  /MV305$04 (9)
  /MV305$05 (9)
  /MV305$06 (9)
  /MV305$07 (9)
  /MV305$08 (9)
  /MV305$09 (9)
  /MV305$10 (9)
  /MV305$11 (9)
  /MV305$12 (9)
  /MV305$13 (9)
  /MV305$14 (9)
  /MV305$15 (9)
  /MV305$16 (9)
  /MV305$17 (9)
  /MV305$18 (9)
  /MV305$19 (9)
  /MV305$20 (9)
  /MV307$01 (9)
  /MV307$02 (9)
  /MV307$03 (9)
  /MV307$04 (9)
  /MV307$05 (9)
  /MV307$06 (9)
  /MV307$07 (9)
  /MV307$08 (9)
  /MV307$09 (9)
  /MV307$10 (9)
  /MV307$11 (9)
  /MV307$12 (9)
  /MV307$13 (9)
  /MV307$14 (9)
  /MV307$15 (9)
  /MV307$16 (9)
  /MV307$17 (9)
  /MV307$18 (9)
  /MV307$19 (9)
  /MV307$20 (9)
  /MV312    (99)
  /MV313    (9)
  /MV323A   (99)
  /MV325B   (9999999)
  /MV372A   (9)
  /MV384A   (9)
  /MV384B   (9)
  /MV384C   (9)
  /MV395    (9)
  /MV396    (9)
  /MV3A09B  (999)
  /MV3B17   (99)
  /MV3B25A  (9)
  /MV3B25B  (9)
  /MV463A   (9)
  /MV463B   (9)
  /MV463C   (9)
  /MV463D   (9)
  /MV463E   (9)
  /MV463F   (9)
  /MV463G   (9)
  /MV463X   (9)
  /MV463Z   (9)
  /MV464    (99)
  /MV474    (9)
  /MV474A   (9)
  /MV474B   (9)
  /MV474C   (9)
  /MV474D   (9)
  /MV474E   (9)
  /MV474F   (9)
  /MV474G   (9)
  /MV474H   (9)
  /MV474I   (9)
  /MV474J   (9)
  /MV474X   (9)
  /MV474Z   (9)
  /MV475    (9)
  /MV476    (9)
  /MV477    (99)
  /MV478    (99)
  /MV479    (99)
  /MV480    (9)
  /MV481    (9)
  /MV481A   (9)
  /MV481B   (9)
  /MV481C   (9)
  /MV481D   (9)
  /MV481E   (9)
  /MV481F   (9)
  /MV481G   (9)
  /MV481H   (9)
  /MV481X   (9)
  /MV482A   (9)
  /MV482B   (9)
  /MV482C   (9)
  /MV483    (9)
  /MV483A   (99)
  /MV483B   (99)
  /MV483C   (99)
  /MV501    (9)
  /MV502    (9)
  /MV503    (9)
  /MV504    (9)
  /MV505    (99)
  /MV525    (99)
  /MV527    (999)
  /MV528    (99)
  /MV529    (999)
  /MV531    (99)
  /MV535    (9)
  /MV536    (9)
  /MV541    (9)
  /MV602    (9)
  /MV603    (999)
  /MV604    (9)
  /MV605    (9)
  /MV613    (99)
  /MV616    (999)
  /MV621    (9)
  /MV627    (99)
  /MV628    (99)
  /MV629    (99)
  /MV631    (9)
  /MV633A   (9)
  /MV633B   (9)
  /MV633C   (9)
  /MV633D   (9)
  /MV633E   (9)
  /MV633F   (9)
  /MV633G   (9)
  /MV634A   (9)
  /MV634B   (9)
  /MV634C   (9)
  /MV634D   (9)
  /MV714    (9)
  /MV714A   (9)
  /MV716    (999)
  /MV717    (99)
  /MV719    (9)
  /MV721    (9)
  /MV731    (9)
  /MV732    (9)
  /MV739    (9)
  /MV740    (9)
  /MV741    (9)
  /MV743A   (9)
  /MV743B   (9)
  /MV743C   (9)
  /MV743D   (9)
  /MV743E   (9)
  /MV743F   (9)
  /MV743G   (9)
  /MV744A   (9)
  /MV744B   (9)
  /MV744C   (9)
  /MV744D   (9)
  /MV744E   (9)
  /MV745A   (9)
  /MV745B   (9)
  /MV747A   (9)
  /MV747B   (9)
  /MV750    (9)
  /MV751    (9)
  /MV754BP  (9)
  /MV754CP  (9)
  /MV754DP  (9)
  /MV754JP  (9)
  /MV754WP  (9)
  /MV756    (9)
  /MV761    (9)
  /MV761B   (9)
  /MV761C   (9)
  /MV762AA  (9)
  /MV762AB  (9)
  /MV762AC  (9)
  /MV762AD  (9)
  /MV762AE  (9)
  /MV762AF  (9)
  /MV762AG  (9)
  /MV762AH  (9)
  /MV762AI  (9)
  /MV762AJ  (9)
  /MV762AK  (9)
  /MV762AL  (9)
  /MV762AM  (9)
  /MV762AN  (9)
  /MV762AO  (9)
  /MV762AP  (9)
  /MV762AQ  (9)
  /MV762AR  (9)
  /MV762AS  (9)
  /MV762AT  (9)
  /MV762AU  (9)
  /MV762AV  (9)
  /MV762AW  (9)
  /MV762AX  (9)
  /MV762AZ  (9)
  /MV762BA  (9)
  /MV762BB  (9)
  /MV762BC  (9)
  /MV762BD  (9)
  /MV762BE  (9)
  /MV762BF  (9)
  /MV762BG  (9)
  /MV762BH  (9)
  /MV762BI  (9)
  /MV762BJ  (9)
  /MV762BK  (9)
  /MV762BL  (9)
  /MV762BM  (9)
  /MV762BN  (9)
  /MV762BO  (9)
  /MV762BP  (9)
  /MV762BQ  (9)
  /MV762BR  (9)
  /MV762BS  (9)
  /MV762BT  (9)
  /MV762BU  (9)
  /MV762BV  (9)
  /MV762BW  (9)
  /MV762BX  (9)
  /MV762BZ  (9)
  /MV763A   (9)
  /MV763B   (9)
  /MV763C   (9)
  /MV763D   (9)
  /MV763E   (9)
  /MV763F   (9)
  /MV763G   (9)
  /MV766A   (99)
  /MV766B   (99)
  /MV767A   (99)
  /MV767B   (99)
  /MV767C   (99)
  /MV768A   (999)
  /MV768B   (999)
  /MV768C   (999)
  /MV769    (9)
  /MV769A   (9)
  /MV770    (9)
  /MV770A   (9)
  /MV770B   (9)
  /MV770C   (9)
  /MV770D   (9)
  /MV770E   (9)
  /MV770F   (9)
  /MV770G   (9)
  /MV770H   (9)
  /MV770I   (9)
  /MV770J   (9)
  /MV770K   (9)
  /MV770L   (9)
  /MV770M   (9)
  /MV770N   (9)
  /MV770O   (9)
  /MV770P   (9)
  /MV770Q   (9)
  /MV770R   (9)
  /MV770S   (9)
  /MV770T   (9)
  /MV770U   (9)
  /MV770V   (9)
  /MV770W   (9)
  /MV770X   (9)
  /MV774A   (9)
  /MV774B   (9)
  /MV774C   (9)
  /MV775    (9)
  /MV777    (9)
  /MV778    (9)
  /MV779    (9)
  /MV780    (9)
  /MV781    (9)
  /MV783    (9)
  /MV784A   (9)
  /MV784B   (9)
  /MV784C   (9)
  /MV784D   (9)
  /MV784E   (9)
  /MV784F   (9)
  /MV784G   (9)
  /MV784H   (9)
  /MV784I   (9)
  /MV784J   (9)
  /MV784K   (9)
  /MV784L   (9)
  /MV784M   (9)
  /MV784N   (9)
  /MV784O   (9)
  /MV784P   (9)
  /MV784Q   (9)
  /MV784R   (9)
  /MV784S   (9)
  /MV784T   (9)
  /MV784U   (9)
  /MV784V   (9)
  /MV784X   (9)
  /MV785    (9)
  /MV791    (9)
  /MV793    (9)
  /MV793A   (9)
  /MV793B   (9)
  /MV820    (9)
  /MV822    (9)
  /MV823    (9)
  /MV824    (9)
  /MV825    (9)
  /MV826    (9)
  /MV826A   (99)
  /MV827    (9)
  /MV828    (9)
  /MV829    (99)
  /MV832B   (999)
  /MV832C   (999)
  /MV833A   (9)
  /MV833B   (9)
  /MV833C   (9)
  /MV834A   (99)
  /MV834B   (99)
  /MV834C   (99)
  /MV835A   (9)
  /MV835B   (9)
  /MV835C   (9)
  /MV836    (99)
  /MV837    (9)
  /MV844    (9)
  /MV845    (9)
  /MV846    (9)
  /MV847    (9)
  /MV848    (9)
  /MV849    (9)
  /MV851A   (9)
  /MV851B   (9)
  /MV851C   (9)
  /MV851D   (9)
  /MV851E   (9)
  /MV851F   (9)
  /MV851G   (9)
  /MV851H   (9)
  /MV851I   (9)
  /MV851J   (9)
  /MV851K   (9)
  /MV851L   (9)
  /MV852A   (999)
  /MV852B   (999)
  /MV852C   (999)
  /MV853A   (99)
  /MV853B   (99)
  /MV853C   (99)
  /MV854A   (9)
  /MV854B   (9)
  /MG100    (9)
  /MG101    (9)
  /MG117A   (9)
  /MG117B   (9)
  /MG117C   (9)
  /MG117D   (9)
  /MG117E   (9)
  /MG117F   (9)
  /MG117G   (9)
  /MG117H   (9)
  /MG117I   (9)
  /MG117J   (9)
  /MG117X   (9)
  /MG117Y   (9)
  /MG118    (9)
  /MG119    (9)
  /SM302D   (9)
  /SM302B1  (9)
  /SM302B2  (9)
  /SM302B3  (9)
  /SM302B4  (9)
  /SM302C1  (9)
  /SM302E1  (9)
  /SM302E2  (9)
  /SM302E3  (9)
  /SM302E4  (9)
  /SM302G1  (9)
  /SM302G2  (9)
  /SM302G3  (9)
  /SM302G4  (9)
  /SM402A   (9)
  /SM707A   (9)
  /SM707B   (9)
  /SM707C   (9)
  /SM707D   (9)
 .
VALUE LABELS
   MV013   
      1 "15-19"
      2 "20-24"
      3 "25-29"
      4 "30-34"
      5 "35-39"
      6 "40-44"
      7 "45-49"
      8 "50-54"
      9 "55-59"
     10 "60-64"
  /MV014   
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /MV015   
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /MV022   
      1 "Urban Centre"
      2 "Rural Centre"
      3 "Urban Centre-Est"
      4 "Rural Centre-Est"
      5 "Urban Centre-Nord"
      6 "Rural Centre-Nord"
      7 "Urban Centre-Ouest"
      8 "Rural Centre-Ouest"
      9 "Urban Nord"
     10 "Rural Nord"
     11 "Urban Nord-est"
     12 "Rural Nord-est"
     13 "Urban Nord-Ouest"
     14 "Rural Nord-Ouest"
     15 "Urban Ouest"
     16 "Rural Ouest"
     17 "Urban Sud sans Abidjan"
     18 "Rural Sud sans Abidjan"
     19 "Urban Sud-ouest"
     20 "Rural Sud-ouest"
     21 "Urban Ville d'Abidjan"
     22 "Rural Ville d'Abidjan"
  /MV023   
      1 "Urban Centre"
      2 "Rural Centre"
      3 "Urban Centre-Est"
      4 "Rural Centre-Est"
      5 "Urban Centre-Nord"
      6 "Rural Centre-Nord"
      7 "Urban Centre-Ouest"
      8 "Rural Centre-Ouest"
      9 "Urban Nord"
     10 "Rural Nord"
     11 "Urban Nord-est"
     12 "Rural Nord-est"
     13 "Urban Nord-Ouest"
     14 "Rural Nord-Ouest"
     15 "Urban Ouest"
     16 "Rural Ouest"
     17 "Urban Sud sans Abidjan"
     18 "Rural Sud sans Abidjan"
     19 "Urban Sud-ouest"
     20 "Rural Sud-ouest"
     21 "Urban Ville d'Abidjan"
     22 "Rural Ville d'Abidjan"
  /MV024   
      1 "Centre"
      2 "Centre-Est"
      3 "Centre-Nord"
      4 "Centre-Ouest"
      5 "Nord"
      6 "Nord-est"
      7 "Nord-Ouest"
      8 "Ouest"
      9 "Sud sans Abidjan"
     10 "Sud-ouest"
     11 "Ville d'Abidjan"
  /MV025   
      1 "Urban"
      2 "Rural"
  /MV026   
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /MV034$1 
      0 "Wife not in household"
  /MV034$2 
      0 "Wife not in household"
  /MV034$3 
      0 "Wife not in household"
  /MV034$4 
      0 "Wife not in household"
  /MV034$5 
      0 "Wife not in household"
  /MV034$6 
      0 "Wife not in household"
  /MV034$7 
      0 "Wife not in household"
  /MV034$8 
      0 "Wife not in household"
  /MV034A$1
      1 "Wife"
      2 "Partner"
  /MV034A$2
      1 "Wife"
      2 "Partner"
  /MV034A$3
      1 "Wife"
      2 "Partner"
  /MV034A$4
      1 "Wife"
      2 "Partner"
  /MV034A$5
      1 "Wife"
      2 "Partner"
  /MV034A$6
      1 "Wife"
      2 "Partner"
  /MV034A$7
      1 "Wife"
      2 "Partner"
  /MV034A$8
      1 "Wife"
      2 "Partner"
  /MV035   
      0 "No wives/partners"
  /MV803   
     95 "95+"
     96 "2+ visits"
     97 "Inconsistent"
  /MV101   
      1 "Centre"
      2 "Centre-Est"
      3 "Centre-Nord"
      4 "Centre-Ouest"
      5 "Nord"
      6 "Nord-est"
      7 "Nord-Ouest"
      8 "Ouest"
      9 "Sud sans Abidjan"
     10 "Sud-ouest"
     11 "Ville d'Abidjan"
  /MV102   
      1 "Urban"
      2 "Rural"
  /MV103   
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
  /MV104   
     95 "Always"
     96 "Visitor"
     97 "Inconsistent"
     98 "Don't know"
  /MV105   
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
  /MV106   
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
  /MV107   
      0 "No years completed at level MV106"
  /MV130   
      1 "Muslim"
      2 "Catholic"
      3 "Methodist"
      4 "Evangelical"
      5 "Other Christian"
      6 "Animist"
      7 "Other religion"
      8 "No religion"
     96 "Other"
  /MV131   
    101 "ABBEY"
    102 "ABIDJI"
    103 "ABOURE"
    104 "ABRON"
    105 "ADJOUKROU"
    319 "AFGHANISTAN"
    234 "AFRIQUE DU SUD"
    200 "AFRIQUE SANS PRECISION"
    106 "AGNI"
    107 "AHIZI"
    110 "AKYE OU ATTIE"
    410 "ALBANIE"
    249 "ALGERIE"
    108 "ALLADIAN"
    421 "ALLEMAGNE"
    500 "AMERIQUE SANS PRECISION"
    240 "ANGOLA"
    700 "APATRIDE"
    109 "APPOLO OU N'ZIMA"
    328 "ARABIE SAOUDITE"
    516 "ARGENTINE"
    428 "ARMENIE"
    300 "ASIE SANS PRECISION"
    601 "AUSTRALIE"
    422 "AUTRICHE"
    111 "AVIKAM OU BRIGNAN"
    429 "AZERBAIDJAN"
    329 "BAHREIN"
    112 "BAKWE"
    113 "BAMBARA"
    320 "BANGLADESH"
    114 "BAOULE"
    430 "BELARUS"
    423 "BELGIQUE"
    501 "BELIZE"
    201 "BENIN"
    115 "BETE"
    321 "BHOUTAN"
    116 "BIRIFOR"
    517 "BOLIVIE"
    411 "BOSNIE-HERZEGOVINE"
    235 "BOTSWANA"
    518 "BRESIL"
    306 "BRUNEI DARUSSALAM"
    431 "BULGARIE"
    202 "BURKINA-FASO"
    217 "BURUNDI"
    307 "CAMBODGE"
    241 "CAMEROUN"
    514 "CANADA"
    203 "CAP VERT"
    242 "CENTRAFRIQUE"
    519 "CHILI"
    301 "CHINE"
    520 "COLOMBIE"
    218 "COMORES"
    243 "CONGO BRAZZAVILLE"
    244 "CONGO KINSHASA ( RDC )"
    117 "CONJA"
    304 "COREE DU NORD"
    305 "COREE DU SUD"
    502 "COSTA RICA"
    412 "CROATIE"
    508 "CUBA"
    401 "DARNEMARK"
    118 "DEGHA"
    119 "DIDA"
    120 "DIOULA"
    227 "DJIBOUTI"
    121 "DJIMINI"
    122 "DOMA"
    123 "EBRIE"
    124 "EGA"
    250 "EGYPTE"
    125 "EHOTILE"
    503 "EL SALVADOR"
    330 "EMIRATS ARABES UNIS"
    521 "EQUATEUR"
    219 "ERYTHREE"
    413 "ESPAGNE"
    126 "ESSOUMA"
    402 "ESTONIE"
    515 "ETATS UNIS D'AMERIQUES"
    220 "ETHIOPIE"
    400 "EUROPE SANS PRECISION"
    308 "FIDJI"
    403 "FINLANDE"
    127 "FOULA"
    424 "FRANCE"
    245 "GABON"
    128 "GAGOU"
    205 "GAMBIE"
    129 "GBIN"
    432 "GEORGIE"
    206 "GHANA"
    130 "GNABOUA ( niaboua )"
    131 "GODIE"
    132 "GOUIN OU KIRMA"
    133 "GOURO"
    414 "GRECE"
    134 "GUERE"
    207 "GUINEE"
    246 "GUINEE EQUATORIALE"
    208 "GUINEE-BISSAU"
    509 "HAÏTI"
    504 "HONDURAS"
    433 "HONGRIE"
    309 "ILES SALOMON"
    322 "INDE"
    310 "INDONESIE"
    323 "IRAN"
    331 "IRAQ"
    404 "IRLANDE"
    332 "ISRAEL"
    415 "ITALIE"
    171 "IVOIRIENS SANS PRECISION"
    510 "JAMAÏQUE"
    302 "JAPON"
    333 "JORDANIE"
    135 "KAMARA OU KOMARA"
    434 "KAZAKHSTAN"
    221 "KENYA"
    435 "KIRGHIZISTAN"
    136 "KODIA"
    137 "KOMONO"
    138 "KORO"
    139 "KOTROHOU"
    140 "KOULANGO"
    141 "KOUYA"
    142 "KOUZIE"
    334 "KOWEIT"
    143 "KOYAKA OU KOYARA"
    144 "KROBOU"
    145 "KROUMEN"
    311 "LAOS"
    236 "LESOTHO"
    405 "LETTONIE"
    335 "LIBAN"
    209 "LIBERIA"
    251 "LIBYE"
    406 "LITUANIE"
    146 "LOBI"
    147 "LOHRON"
    425 "LUXEMBOURG"
    416 "MACEDOINE"
    222 "MADAGASCAR"
    148 "MAHOU OU MAHOUKA"
    312 "MALAISIE"
    237 "MALAWI"
    324 "MALDIVES"
    210 "MALI"
    149 "MALINKE OU MANINKA"
    417 "MALTE"
    252 "MAROC"
    223 "MAURICE"
    211 "MAURITANI"
    150 "M'BATTO ( goua )"
    602 "MELANESIE"
    505 "MEXIQUE"
    438 "MOLDAVA (Répulique)"
    151 "MONA OU MOUAN"
    303 "MONGOLIE"
    224 "MOZAMBIQUE"
    313 "MYANMAR"
    152 "NAFANA"
    238 "NAMIBIE"
    170 "NATURALISE IVOIRIEN"
    325 "NEPAL"
    153 "NEYO"
    154 "N'GAIN"
    506 "NICARAGUA"
    155 "NIEDEBOUA"
    156 "NIGBI"
    212 "NIGER"
    213 "NIGERIA"
    407 "NORVEGE"
    603 "NOUVELLE CALEDONIE"
    604 "NOUVELLE ZELANDE"
    600 "OCEANIE SANS PRECISION"
    336 "OMAN"
    157 "OUADOUGOU"
    158 "OUAN"
    159 "OUBI"
    225 "OUGANDA"
    160 "OUODOUGOU"
    436 "OUZBEKISTAN"
    326 "PAKISTAN"
    507 "PANAMA"
    605 "PAPOUASIE NOUVELLE GUINEE"
    522 "PARAGUAY"
    426 "PAYS-BAS"
    523 "PEROU"
    314 "PHILIPPINES"
    437 "POLOGNE"
    511 "PORTO RICO"
    418 "PORTUGAL"
    337 "QATAR"
    512 "REPUBLIQUE DOMINICAINE"
    440 "ROUMANIE"
    408 "ROYAUME-UNI"
    441 "RUSSIE"
    226 "RWANDA"
    315 "SAMOA OCCIDENTAL"
    161 "SAMOGHO"
    247 "SAO TOME & PRINCIPE"
    214 "SENEGAL"
    162 "SENOUFO"
    228 "SEYCHELLES"
    215 "SIERRA LEONE"
    316 "SINGAPOUR"
    163 "SITI"
    442 "SLOVAQUIE"
    419 "SLOVENIE"
    229 "SOMALIE"
    230 "SOUDAN"
    327 "SRI LANKA"
    409 "SUEDE"
    427 "SUISSE"
    239 "SWAZILAND"
    338 "SYRIE"
    443 "TADJISKISTAN"
    164 "TAGOUANA"
    231 "TANZANIE"
    248 "TCHAD"
    439 "TCHEQUE (République)"
    317 "THAILAND"
    216 "TOGO"
    165 "TOURA"
    513 "TRINITE ET TOBAGO"
    253 "TUNISIE"
    444 "TURKMENISTAN"
    339 "TURQUIE"
    445 "UKRAINE"
    524 "URUGUAY"
    606 "VANUATU"
    525 "VENEZUELA"
    318 "VIET-NAM"
    166 "WANE"
    167 "WOBE"
    168 "YACOUBA OU DAN"
    169 "YAOURE ( yohouré )"
    340 "YEMEN"
    420 "YOUGOSLAVIE"
    232 "ZAMBIE"
    233 "ZIMBABWE"
  /MV133   
     97 "Inconsistent"
  /MV134   
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /MV135   
      1 "Usual resident"
      2 "Visitor"
  /MV149   
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
  /MV150   
      1 "Head"
      2 "Husband"
      3 "Son"
      4 "Son-in-law"
      5 "Grandson"
      6 "Father"
      7 "Father-in-law"
      8 "Brother"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     98 "Don't know"
  /MV151   
      1 "Male"
      2 "Female"
  /MV152   
     97 "97+"
     98 "Don't know"
  /MV155   
      0 "Cannot read at all"
      1 "Able to read only parts of sentence"
      2 "Able to read whole sentence"
      3 "No card with required language"
      4 "Blind/visually impaired"
  /MV156   
      0 "No"
      1 "Yes"
  /MV157   
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /MV158   
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /MV159   
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /MV167   
      0 "None"
     90 "90+"
     97 "Inconsistent"
     98 "Don't know"
  /MV168   
      0 "No"
      1 "Yes"
  /MV190   
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /MV212   
     97 "Inconsistent"
  /MV213   
      0 "No"
      1 "Yes"
      8 "Unsure"
  /MV217   
      1 "During her period"
      2 "After period ended"
      3 "Middle of the cycle"
      4 "Before period begins"
      5 "At any time"
      6 "Other"
      8 "Don't know"
  /MV225   
      1 "Then"
      2 "Later"
      3 "Not at all"
  /MV246   
      0 "No"
      1 "Yes"
  /MV248   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV249   
      0 "Not present"
      1 "Present"
  /MV250   
      1 "Hospital, health facility"
      2 "Other"
  /MV251   
      1 "Cost too much"
      2 "Facility closed"
      3 "Too far/no transportation"
      4 "Don't trust facility/poor quality service"
      5 "No female provider"
      6 "Not the first child"
      7 "Mother did not think it necessary"
      8 "Respondent did not think it necessary"
      9 "Family did not think it necessary"
     96 "Other"
     98 "Don't know"
  /MV252   
      0 "Nothing to drink"
      2 "Less than usual/much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /MV301   
      0 "Knows no method"
      1 "Knows only folkloric method"
      2 "Knows only traditional method"
      3 "Knows modern method"
  /MV302   
      0 "Never used"
      1 "Used only folkloric method"
      2 "Used only traditional method"
      3 "Used modern method"
  /M304A$01
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$02
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$03
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$04
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$05
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$06
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$07
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$08
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$09
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$10
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$11
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$12
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$13
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$14
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$15
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$16
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$17
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$18
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$19
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /M304A$20
      1 "Modern method"
      2 "Traditional method"
      3 "Folkloric method"
  /MV304$01
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$02
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$03
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$04
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$05
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$06
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$07
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$08
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$09
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$10
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$11
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$12
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$13
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$14
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$15
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$16
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$17
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$18
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$19
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV304$20
      0 "No"
      1 "Yes"
      7 "Not in contraception table, but as a current method"
      8 "Not asked"
  /MV305$01
      0 "No"
      1 "Yes"
  /MV305$02
      0 "No"
      1 "Yes"
  /MV305$03
      0 "No"
      1 "Yes"
  /MV305$04
      0 "No"
      1 "Yes"
  /MV305$05
      0 "No"
      1 "Yes"
  /MV305$06
      0 "No"
      1 "Yes"
  /MV305$07
      0 "No"
      1 "Yes"
  /MV305$08
      0 "No"
      1 "Yes"
  /MV305$09
      0 "No"
      1 "Yes"
  /MV305$10
      0 "No"
      1 "Yes"
  /MV305$11
      0 "No"
      1 "Yes"
  /MV305$12
      0 "No"
      1 "Yes"
  /MV305$13
      0 "No"
      1 "Yes"
  /MV305$14
      0 "No"
      1 "Yes"
  /MV305$15
      0 "No"
      1 "Yes"
  /MV305$16
      0 "No"
      1 "Yes"
  /MV305$17
      0 "No"
      1 "Yes"
  /MV305$18
      0 "No"
      1 "Yes"
  /MV305$19
      0 "No"
      1 "Yes"
  /MV305$20
      0 "No"
      1 "Yes"
  /MV307$01
      0 "No"
      1 "Yes"
  /MV307$02
      0 "No"
      1 "Yes"
  /MV307$03
      0 "No"
      1 "Yes"
  /MV307$04
      0 "No"
      1 "Yes"
  /MV307$05
      0 "No"
      1 "Yes"
  /MV307$06
      0 "No"
      1 "Yes"
  /MV307$07
      0 "No"
      1 "Yes"
  /MV307$08
      0 "No"
      1 "Yes"
  /MV307$09
      0 "No"
      1 "Yes"
  /MV307$10
      0 "No"
      1 "Yes"
  /MV307$11
      0 "No"
      1 "Yes"
  /MV307$12
      0 "No"
      1 "Yes"
  /MV307$13
      0 "No"
      1 "Yes"
  /MV307$14
      0 "No"
      1 "Yes"
  /MV307$15
      0 "No"
      1 "Yes"
  /MV307$16
      0 "No"
      1 "Yes"
  /MV307$17
      0 "No"
      1 "Yes"
  /MV307$18
      0 "No"
      1 "Yes"
  /MV307$19
      0 "No"
      1 "Yes"
  /MV307$20
      0 "No"
      1 "Yes"
  /MV312   
      0 "Not using"
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female Sterilization"
      7 "Male Sterilization"
      8 "Periodic Abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Implants/Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea (LAM)"
     14 "Female condom"
     15 "Foam or jelly"
     17 "Other modern method"
     18 "Survey Specific method 2"
     19 "Survey Specific method 3"
     20 "Survey Specific method 4"
     98 "Don't know"
  /MV313   
      0 "No method"
      1 "Folkloric method"
      2 "Traditional method"
      3 "Modern method"
      8 "Don't know"
  /MV323A  
      1 "Prudence"
      2 "IPPF"
      3 "Kamassoutra"
     96 "Other"
     98 "Don't know"
  /MV325B  
   9999995 "Free"
   9999998 "Don't know"
  /MV372A  
      0 "Package not seen"
      1 "Package seen"
  /MV384A  
      0 "No"
      1 "Yes"
  /MV384B  
      0 "No"
      1 "Yes"
  /MV384C  
      0 "No"
      1 "Yes"
  /MV395   
      0 "No"
      1 "Yes"
      2 "Depends"
      8 "Don't know"
  /MV396   
      0 "No"
      1 "Yes"
      2 "Depends"
      8 "Don't know"
  /MV3A09B 
    998 "Don't know"
  /MV3B17  
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Family planning clinic"
     14 "Mobile clinic"
     15 "Field worker"
     16 "Other public sector"
     20 "PRIVATE SECTOR"
     21 "Private hospital/clinic"
     22 "Pharmacy"
     23 "Private doctor"
     24 "Mobile clinic"
     25 "Field worker"
     26 "Other private medical"
     30 "OTHER"
     31 "Shop"
     32 "Religious institution"
     33 "Friends/relatives"
     96 "Other"
  /MV3B25A 
      0 "Disagree"
      1 "Agree"
      8 "Don't know"
  /MV3B25B 
      0 "Disagree"
      1 "Agree"
      8 "Don't know"
  /MV463A  
      0 "No"
      1 "Yes"
  /MV463B  
      0 "No"
      1 "Yes"
  /MV463C  
      0 "No"
      1 "Yes"
  /MV463D  
      0 "No"
      1 "Yes"
  /MV463E  
      0 "No"
      1 "Yes"
  /MV463F  
      0 "No"
      1 "Yes"
  /MV463G  
      0 "No"
      1 "Yes"
  /MV463X  
      0 "No"
      1 "Yes"
  /MV463Z  
      0 "No"
      1 "Yes, smokes nothing"
  /MV464   
     98 "DK"
  /MV474   
      0 "No"
      1 "Yes"
  /MV474A  
      0 "No"
      1 "Yes"
  /MV474B  
      0 "No"
      1 "Yes"
  /MV474C  
      0 "No"
      1 "Yes"
  /MV474D  
      0 "No"
      1 "Yes"
  /MV474E  
      0 "No"
      1 "Yes"
  /MV474F  
      0 "No"
      1 "Yes"
  /MV474G  
      0 "No"
      1 "Yes"
  /MV474H  
      0 "No"
      1 "Yes"
  /MV474I  
      0 "No"
      1 "Yes"
  /MV474J  
      0 "No"
      1 "Yes"
  /MV474X  
      0 "No"
      1 "Yes"
  /MV474Z  
      0 "No"
      1 "Yes"
  /MV475   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV476   
      0 "No"
      1 "Yes, remain a secret"
      8 "Don't know/not sure/depends"
  /MV477   
      0 "None"
     90 "90+"
     98 "Don't know"
  /MV478   
      0 "None"
     90 "90+"
     98 "Don't know"
  /MV479   
     10 "PUBLIC SECTOR"
     20 "PRIVATE SECTOR"
     30 "OTHER"
     96 "Other"
  /MV480   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV481   
      0 "No"
      1 "Yes"
  /MV481A  
      0 "No"
      1 "Yes"
  /MV481B  
      0 "No"
      1 "Yes"
  /MV481C  
      0 "No"
      1 "Yes"
  /MV481D  
      0 "No"
      1 "Yes"
  /MV481E  
      0 "No"
      1 "Yes"
  /MV481F  
      0 "No"
      1 "Yes"
  /MV481G  
      0 "No"
      1 "Yes"
  /MV481H  
      0 "No"
      1 "Yes"
  /MV481X  
      0 "No"
      1 "Yes"
  /MV482A  
      0 "No"
      1 "Yes"
      8 "Unsure"
  /MV482B  
      0 "No"
      1 "Yes"
  /MV482C  
      0 "No"
      1 "Yes"
      8 "Unsure"
  /MV483   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV483A  
     95 "During childhood <5 years"
     98 "Don't know"
  /MV483B  
      1 "Traditional practitioner / family friend"
      2 "Health worker / professional"
     96 "Other"
     98 "Don't know"
  /MV483C  
      1 "Health facility"
      2 "Home of a health worker / professional"
      3 "Circumcision done at home"
      4 "Ritual site"
     96 "Other home / place"
     98 "Don't know"
  /MV501   
      0 "Never in union"
      1 "Married"
      2 "Living with partner"
      3 "Widowed"
      4 "Divorced"
      5 "No longer living together/separated"
  /MV502   
      0 "Never in union"
      1 "Currently in union/living with a woman"
      2 "Formerly in union/living with a woman"
  /MV503   
      1 "Once"
      2 "More than once"
  /MV504   
      1 "Living with him"
      2 "Staying elsewhere"
  /MV510   
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /MV513   
      0 "Never married"
      1 "0-4"
      2 "5-9"
      3 "10-14"
      4 "15-19"
      5 "20-24"
      6 "25-29"
      7 "30+"
  /MV525   
      0 "Not had sex"
     96 "At first union"
     97 "Inconsistent"
     98 "Don't know"
  /MV527   
    100 "<1 day ago"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /MV528   
     31 "31+ days"
     95 "Within last 4 weeks"
     96 "Before last birth"
     97 "Inconsistent"
     98 "Don't know"
  /MV529   
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /MV531   
      0 "Not had sex"
     97 "Inconsistent"
     98 "Don't know"
  /MV532   
      0 "No flag"
      1 "After interview"
      2 "After conception >= 1 year"
      3 "After conception < 1 year"
      4 "At marriage, but never married"
      5 "At marriage, but after conception"
      6 "After marriage"
  /MV535   
      0 "No"
      1 "Formerly married"
      2 "Formerly lived with a woman"
      3 "Both, formerly married and lived with a woman"
  /MV536   
      0 "Never had sex"
      1 "Active in last 4 weeks"
      3 "Not active in last 4 weeks"
  /MV541   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV602   
      1 "Have another"
      2 "Undecided"
      3 "No more"
      4 "Sterilized (respondent or partner(s))"
      5 "Declared infecund (respondent or partner(s))"
      6 "Never had sex"
      7 "Man declared infecund"
      8 "Man has no partner"
  /MV603   
    100 "Wanted now"
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    993 "After marriage"
    994 "Soon, now"
    996 "Other, non-numeric"
    997 "Inconsistent"
    998 "Don't know"
  /MV604   
      0 "<12 months"
      1 "1 year"
      2 "2 years"
      3 "3 years"
      4 "4 years"
      5 "5 years"
      6 "6+ years"
      7 "Non-numeric"
      8 "Don't know"
  /MV605   
      1 "Wants within 2 years"
      2 "Wants after 2+ years"
      3 "Wants, unsure timing"
      4 "Undecided"
      5 "Wants no more"
      6 "Sterilized (respondent or partner(s))"
      7 "Declared infecund (respondent or partner(s))"
      8 "Never had sex"
  /MV613   
     96 "Non-numeric response"
     98 "Don't know"
  /MV614   
      6 "6+"
      7 "Non-numeric response"
  /MV616   
    100 "Wanted now"
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    993 "After marriage"
    994 "Soon/now"
    995 "Can't get pregnant"
    996 "Other"
    998 "Don't know"
  /MV621   
      1 "Both want same"
      2 "Wife wants more"
      3 "Wife wants fewer"
      8 "Don't know"
  /MV627   
     96 "Other"
     98 "Don't know"
  /MV628   
     96 "Other"
     98 "Don't know"
  /MV629   
     96 "Other"
     98 "Don't know"
  /MV631   
      1 "Big problem"
      2 "Small problem"
      3 "No problem"
      4 "Says she can't get pregnant/not having sex"
  /MV633A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV633G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV634A  
      0 "No"
      1 "Yes"
      8 "Don't know, depends"
  /MV634B  
      0 "No"
      1 "Yes"
      8 "Don't know, depends"
  /MV634C  
      0 "No"
      1 "Yes"
      8 "Don't know, depends"
  /MV634D  
      0 "No"
      1 "Yes"
      8 "Don't know, depends"
  /MV714   
      0 "No"
      1 "Yes"
  /MV714A  
      0 "No"
      1 "Yes"
  /MV716   
      0 "Not working"
      1 "Président de la république"
      2 "Chef du gouvernement"
      3 "Ministre, Secrétaire d'Etat et assimilés"
      4 "Gouverneur, Haut commissaire"
      5 "Député, Sénateur"
      6 "Maire"
      7 "Conseiller municipale"
      8 "Membre de l'exécutif et du corps législatif non classé ailleurs"
      9 "Secrétaire général (ministère)"
     10 "Directeur de cabinet (ministre)"
     11 "Administrateur"
     12 "Inspecteur d'Etat"
     13 "Directeur général (Directeur national)"
     14 "Directeur (chef de division)"
     15 "Ambassadeur"
     16 "Chargé d'affaires"
     17 "Consul général"
     18 "Secrétaire d'ambassade"
     19 "Préfet"
     20 "Préfet de police"
     21 "Trésorier payeur général"
     22 "Cadres supérieurs de l'administration publique non classés ailleurs"
     23 "Chef coutumier"
     24 "Chef de village"
     25 "Chef de quartier"
     26 "Dirigeant de parti politique"
     27 "Cadre supérieur de partie politique"
     28 "Dirigeant syndical"
     29 "Cadre supérieur de syndicat"
     30 "Dirigeant d'organisation d'employeurs"
     31 "Cadre supérieur d'organisation d'employeurs"
     32 "Dirigeant d'organisation humanitaire, d'ONGs et d'associations"
     33 "Cadre supérieur d'organisation humanitaire, ONG, associations"
     34 "Dirigeants et cadres supérieurs d'organismes spécialisés non classés ailleurs"
     35 "Chef d'entreprise"
     36 "Administrateur, gérant d'entreprise"
     37 "Directeur d'entreprise"
     38 "Directeur général d'entreprise"
     39 "Président directeur général"
     40 "Industriel"
     41 "Directeur, lycée et  collège"
     42 "Recteur, université"
     43 "Cadre de direction"
     44 "Directeurs cadre de société non classés ailleurs"
     45 "Physicien"
     46 "Climatologiste, climatologue"
     47 "Ingénieurs météorologiste"
     48 "Météorologue"
     49 "Chimiste"
     50 "Géologue"
     51 "Ingénieur géologue"
     52 "Hydrologiste"
     53 "Physiciens, chimistes et assimilés non classés ailleurs"
     54 "Mathématicien"
     55 "Actuaire"
     56 "Statisticien"
     57 "Démographe"
     58 "Mathématiciens, statisticiens et assimilés non classés ailleurs"
     59 "Informaticien"
     60 "Programmeur"
     61 "Spécialistes de l'informatique non classés ailleurs"
     62 "Architecte"
     63 "Urbaniste"
     64 "Ingénieur, génie civil"
     65 "Ingénieur, génie rural"
     66 "Ingénieurs, ponts et chaussées"
     67 "Technicien supérieur, génie civil"
     68 "Technicien supérieur, génie rural"
     69 "Ingénieur électricien"
     70 "Ingénieur électronicien"
     71 "Ingénieur des télécommunications"
     72 "Technicien supérieur/électricien"
     73 "Technicien supérieur/télécommunication"
     74 "Ingénieur frigoriste"
     75 "Ingénieur mécanicien"
     76 "Ingénieur naval"
     77 "Ingénieur chimiste"
     78 "Technicien supérieur, chimie"
     79 "Ingénieur des mines"
     80 "Ingénieur métallurgiste"
     81 "Ingénieur sidérurgiste"
     82 "Technicien supérieur, métallurgiste"
     83 "Cartographe"
     84 "Géomètre"
     85 "Architectes, ingénieurs et assimilés non classés ailleurs"
     86 "Bactériologiste"
     87 "Biologiste"
     88 "Botaniste"
     89 "Biochimiste"
     90 "Ecologiste"
     91 "Zoologiste"
     92 "Anatomiste"
     93 "Biophysicien"
     94 "Pathologiste"
     95 "Pharmacologue"
     96 "Physiologiste"
     97 "Toxicologue"
     98 "Agronome"
     99 "Ingénieur agronome, agricole"
    100 "Ingénieur forestier"
    101 "Pédologue"
    102 "Spécialistes des sciences de la vie non classés ailleurs"
    103 "Médecin généraliste"
    104 "Médecin spécialiste (chirurgie, gynécologie, pédiatre, ophtalmologue, orthopédiste)"
    105 "Dentiste"
    106 "Vétérinaire"
    107 "Pharmacien"
    108 "Médecins et assimilés non classés ailleurs"
    109 "Infirmier diplômé"
    110 "Sage-femme diplômé"
    111 "Cadres infirmiers non classés ailleurs"
    112 "Chargé de cours, université"
    113 "Professeur d'université (assistant, maître assistant, maître de conférences)"
    114 "Chercheur (attaché de recherches, chargé de recherches,"
    115 "Directeur de recherches, maître de recherches"
    116 "Professeur d'enseignement secondaire"
    117 "Enseignant, éducation spéciale (sourds, aveugle, handicapé)"
    118 "Inspecteur d'enseignement (primaire ou secondaire)"
    119 "Conseiller pédagogique"
    120 "Autre spécialiste de l'enseignement NCA"
    121 "Cadre comptable"
    122 "Chef comptable"
    123 "Expert-comptable"
    124 "Vérificateur de compte"
    125 "Cadres comptables non classés ailleurs"
    126 "Spécialistes, gestion des ressources humaines"
    127 "Spécialistes des fonctions administratives et commerciales des entreprises non classés ailleurs"
    128 "Avocat"
    129 "Juge"
    130 "Magistrat"
    131 "Greffier"
    132 "Huissier"
    133 "Notaire"
    134 "Juriste non classé ailleurs"
    135 "Archivistes"
    136 "Conservateur"
    137 "Bibliothécaire"
    138 "Documentaliste"
    139 "Archivistes, bibliothécaires, documentalistes et assimilés non classés ailleurs"
    140 "Economiste"
    141 "Anthropologue"
    142 "Archéologue"
    143 "Ethnologue"
    144 "Criminologue"
    145 "Géographe"
    146 "Sociologue"
    147 "Historien"
    148 "Philosophe"
    149 "Politologue, spécialiste des sciences politiques"
    150 "Interprète"
    151 "Linguiste"
    152 "Traducteur"
    153 "Psychologue"
    154 "Animateur, centre communautaire"
    155 "Assistant médico-social"
    156 "Assistant social"
    157 "Spécialistes du travail social non classés ailleurs"
    158 "Spécialistes des sciences sociales et humaines Non classés ailleurs"
    159 "Auteurs"
    160 "Biographe"
    161 "Chroniqueur"
    162 "Commentateur (radio, télé, sport)"
    163 "Correspondant (presse, journaux)"
    164 "Critique"
    165 "Journaliste"
    166 "Poète"
    167 "Romancier"
    168 "scénariste"
    169 "Auteurs, journalistes et autres écrivains non classés ailleurs"
    170 "Artiste peintre"
    171 "Dessinateur (publicité, bandes dessinées, etc.)"
    172 "Sculpteur"
    173 "Musicien (guitariste, pianiste, saxophoniste)"
    174 "Chanteur, cantatrice"
    175 "Compositeur"
    176 "Chorégraphe"
    177 "Danseur"
    178 "Acteur, comédien"
    179 "Metteur en scène (théâtre, cinéma, télévision)"
    180 "Réalisateur (cinéma, télévision, radio)"
    181 "Acteurs et metteurs en scènes de cinéma, de théâtres et d'autres spectacles non classés ailleurs"
    182 "Personnel du culte chrétien"
    183 "Personnel du culte musulman (marabout, imam, maître coranique)"
    184 "Administrateur civil"
    185 "Attaché administratif"
    186 "Cadre supérieur de police (Commissaire, inspecteur de police)"
    187 "Inspecteur des affaires administratives"
    188 "Inspecteur du travail et des lois sociales"
    189 "Cadre supérieur de la sécurité sociale"
    190 "Attaché d'intendance universitaire"
    191 "proviseur"
    192 "censeur"
    193 "Administrateur et attachés des hôpitaux"
    194 "ingénieur sanitaire"
    195 "Autre cadres supérieurs des affaires sociales"
    196 "nutritionniste"
    197 "Diététicien"
    198 "Assistant de santé, attaché de santé"
    199 "Assistant médical"
    200 "Assistant dentiste"
    201 "Assistant pharmacien"
    202 "Préparateur en pharmacie"
    203 "Kinésithérapeute"
    204 "Masseur"
    205 "Opticien"
    206 "Technicien de radiologie médicale"
    207 "Praticien de médecine traditionnelle et guérisseurs"
    208 "inspecteur des T.P."
    209 "Ingénieur de l'équipement rural et de l'hydraulique"
    210 "cadre sup. des P et T (Ingénieur des P et T, Administrateur des P et T)"
    211 "cadre sup. et technicien de l'équipement rural"
    212 "Inspecteur mécanicien, marine marchande"
    213 "Officier mécanicien, navire"
    214 "Officier de navigation"
    215 "Pilote de navire"
    216 "Mécanicien navigant, avion"
    217 "Pilote d'avion"
    218 "Contrôleur de la circulation aérienne"
    219 "Technicien, sécurité aérienne"
    220 "Instructeur, navigation"
    221 "Moniteur, auto-école"
    222 "Courtier maritime"
    223 "Agent maritime"
    224 "Agent, dédouanement"
    225 "Déclarant en douane"
    226 "Transitaire"
    227 "Cadre supérieur des affaires économiques"
    228 "Cadre supérieur de banque"
    229 "Cadre supérieur des assurances"
    230 "Inspecteur des douanes"
    231 "Inspecteurs des impôts"
    232 "Inspecteurs du trésor"
    233 "Autres cadre sup. des ressources financières (trésor, impôts, douanes, domaine, enregistrement)"
    234 "Administrateur des services fiscaux et des services financiers"
    235 "Planificateur"
    236 "Autres cadres supérieurs statisticiens et démographes"
    237 "Contrôleur des prix"
    238 "Contrôleur de qualité"
    239 "Conseiller agricole"
    240 "Conseiller forestier"
    241 "Vulgarisateur agricole"
    242 "Ingénieur et conseiller FJA (Formateur de Jeunes Agriculteurs)"
    243 "Autres cadres sup. de l'agriculture"
    244 "Autres cadres sup. des Eaux et Forêts et de pêche"
    245 "Autres cadres sup. de l'élevage"
    246 "Autres techniciens des sciences biologiques  et agronomiques"
    247 "Autres cadres supérieurs de la géologie et des mines non classés ailleurs"
    248 "Président de la cour d'appel"
    249 "Cadre sup. des affaires étrangères"
    250 "Cadre sup. de la presse et de la communication"
    251 "Décorateur, dessinateur de modèle"
    252 "Caméraman (cinéma, télévision)"
    253 "Photographe (commercial, industriel, presse, publicitaire)"
    254 "Manageur sportif"
    255 "Professeur d'éducation permanente et physique"
    256 "Inspecteur de la jeunesse et des sports"
    257 "Conseiller de la jeunesse et d'animation"
    258 "Administrateur des affaires culturelles"
    259 "Cadre sup. des services touristiques et hôteliers"
    260 "Technicien chimiste"
    261 "Technicien de laboratoire"
    262 "Technicien géologue"
    263 "Technicien physicien"
    264 "Technicien géomètre"
    265 "Technicien météorologiste"
    266 "Technicien de génie civil"
    267 "Electrotechnicien"
    268 "Technicien électronicien"
    269 "Technicien des télécommunications"
    270 "Technicien frigoriste"
    271 "Technicien mécanicien"
    272 "Technicien métallurgiste"
    273 "Technicien, mines"
    274 "Dessinateur (industriel, génie civil)"
    275 "Assistant informatique"
    276 "Technicien, appareil audio-visuel"
    277 "Technicien appareil médical"
    278 "Technicien spécialiste des sciences de la vie (biologiste, botanique)"
    279 "Professions intermédiaires - cadres supérieurs non classés ailleurs"
    280 "Secrétaire de direction"
    281 "Secrétaire administratif"
    282 "Contrôleur de travail"
    283 "Assistant administratif"
    284 "Maître, instituteur, enseignement primaire"
    285 "Maître, instituteur, enseignement pré primaire"
    286 "Jardinière d'enfants"
    287 "Moniteur, enseignement pré primaire"
    288 "Educateur spécialisés (aveugle, sourds, etc.)"
    289 "Assistant FJA (Formateur de Jeunes Agriculteurs)"
    290 "Surveillant de lycées et collèges"
    291 "Maître d'éducation physique et sportive - Educateur sportif"
    292 "Cadre moyen de la documentation"
    293 "infirmier d'Etat spécialisé et breveté"
    294 "sage-femme d'Etat ou spécialisée"
    295 "Technicien et assistant d'assainissement"
    296 "Prothésiste dentaire"
    297 "Laborantin"
    298 "Gestionnaire des hôpitaux"
    299 "Aide sociale - éducateur social"
    300 "Puéricultrice"
    301 "Autre cadre moyen de santé et de l'action sociale"
    302 "Chef de chantier"
    303 "Chef mécanicien"
    304 "Adjoint technique des T.P."
    305 "Contrôleur - receveur des P et T"
    306 "Assistant météorologiste et de la navigation aérienne"
    307 "Technicien du génie rural"
    308 "Contremaître"
    309 "Contrôleur des impôts"
    310 "Contrôleurs des douanes"
    311 "Contrôleur du trésor"
    312 "Percepteur"
    313 "Comptable"
    314 "Autres cadres moyens du budget, des ressources financières"
    315 "Assistant des affaires économiques et économe"
    316 "Assistant statisticien (adjoint technique de la statistique)"
    317 "Assistant, actuaire"
    318 "Assistant comptable"
    319 "Technicien agronome"
    320 "Technicien forestier"
    321 "Assistant vétérinaire"
    322 "Conducteur des travaux agricoles"
    323 "agent technique d'agriculture spécialisé"
    324 "Contrôleurs des eaux et forêts"
    325 "Assistant et agent technique d'élevage spécialisé"
    326 "Technicien de la géologie et des mines"
    327 "Mandataire de justice"
    328 "Secrétaire des affaires étrangères"
    329 "Agent de maîtrise de l'information"
    330 "Reporter, speaker, animateur (radio et télévision)"
    331 "Arbitre, sport"
    332 "Entraîneur"
    333 "Moniteur sportif"
    334 "Athlète professionnel (coureur, footballeur, boxeur)"
    335 "Lutteur professionnel"
    336 "Jockey"
    337 "Moniteur, culture sportive"
    338 "autres professions intermédiaires - cadre moyen NCA"
    339 "Agent de police"
    340 "Animateur rural"
    341 "Encadreur d'agriculture (Organisme de développement rural)"
    342 "Moniteur et formateur de jeunes agriculteurs (FJA)"
    343 "Préposé des eaux et forêt"
    344 "Agent technique d'agriculture et d'élevage"
    345 "Infirmier vétérinaire"
    346 "Employé de service administratif"
    347 "Adjoint administratif"
    348 "Aide- comptable"
    349 "Caissier, Guichetier"
    350 "Cadre subalterne du budget, et des ressources financières"
    351 "Agent administratif"
    352 "Agent de bureau (de recouvrement, des services fiscaux, de constatation d'assiette)"
    353 "Collecteur d'impôt"
    354 "Agent de douane, préposé des douanes"
    355 "Préposé, contrôle économique"
    356 "Cadre subalterne des affaires économiques - préposé des affaires économiques"
    357 "Secrétaire"
    358 "Dactylographe"
    359 "Standardiste - réceptionniste - téléphoniste"
    360 "planton - agent de liaison - commis d'administration"
    361 "relieur -  reprographe"
    362 "agent et assistant technique de la statistique"
    363 "Agent de saisie, opérateur sur machine"
    364 "Agent de change"
    365 "Courtier, bourse"
    366 "Agent d'assurances"
    367 "Assureur"
    368 "Courtier, assurances"
    369 "Agent immobilier"
    370 "Courtier, immobilier"
    371 "Agent de voyages"
    372 "Agent commercial"
    373 "Démarcheur commercial"
    374 "Agent d'approvisionnement"
    375 "Commissaire-priseur"
    376 "Opérateur topographe"
    377 "Cheminot"
    378 "Opérateur du génie rural"
    379 "Agent de maîtrise de la géologie et des mines"
    380 "Cadre subalterne des transmissions météo"
    381 "Aide météo"
    382 "Cadre subalterne des P et T, facteur, opérateur des téléphones et télégraphes"
    383 "Surveillant des télécommunications"
    384 "Garçon ou fille de salle"
    385 "Agent itinérant de santé"
    386 "Distributeur de comprimés"
    387 "Aide infirmier - aide-soignant"
    388 "Accoucheuse auxiliaire - matrone"
    389 "Aide-laborantin"
    390 "Agent d'hygiène ; d'assainissement"
    391 "Autre personnel de santé subalterne"
    392 "Employé de bibliothèque, classeurs archivistes"
    393 "Employé d'approvisionnement"
    394 "Manoeuvre"
    395 "Ouvrier"
    396 "Magasinier"
    397 "Vérificateur"
    398 "Employé de bureau non classé ailleurs"
    399 "autre personnel du type administratif et cadre subalterne de l'administration NCA"
    400 "Hôtesse, steward"
    401 "Chef de train"
    402 "Receveur (de train, du bus)"
    403 "Guide"
    404 "Boy-cuisinier, Gouvernante"
    405 "Chef de cuisine, cuisinier"
    406 "Pâtissier"
    407 "Boulanger"
    408 "Charcutier"
    409 "Poissonnier"
    410 "Presseur d'huile"
    411 "Barman"
    412 "maître et gérant d'hôtel"
    413 "serveur de restaurant - garçon d'hôtel"
    414 "propriétaires de restaurants"
    415 "servante de bar"
    416 "taxi man - conducteur de bus"
    417 "Chauffeur"
    418 "coiffeur - coiffeuse"
    419 "Barbier"
    420 "laveur - nettoyeur"
    421 "Baby-sitter"
    422 "Astrologue, Diseur de bonne aventure"
    423 "Mannequins, modèles"
    424 "Garde de corps"
    425 "Détective, police privée"
    426 "Commis de magasin"
    427 "Pompiste"
    428 "Vendeur, établissement de commerce"
    429 "Commerçant (propriétaire, gérant de commerce de gros et de détail)"
    430 "Boutiquier"
    431 "vendeur de tissus et friperie"
    432 "vendeur de fruits"
    433 "vendeur de céréales"
    434 "vendeur de vivres frais (alloco, igname, taro, autres féculents)"
    435 "vendeur de beignets et d'autres aliments préparés (vendeur d'aliments)"
    436 "vendeur de légumes et arachides et tous condiments"
    437 "aide vendeur"
    438 "conseiller commercial"
    439 "Libraire"
    440 "Boucher"
    441 "Meunier"
    442 "Marchand de bois"
    443 "Gargotier/dibitier"
    444 "autres métiers de service et vendeurs NCA"
    445 "Cultivateur/Planteur"
    446 "Maraîcher"
    447 "Jardinier"
    448 "exploitant de verger - pépiniériste"
    449 "Exploitant forestier"
    450 "Bûcheron"
    451 "éleveur de bétail"
    452 "éleveur de volaille"
    453 "berger - garde-animaux"
    454 "Pêcheur"
    455 "marin pêcheur"
    456 "Chasseur"
    457 "Apiculteur"
    458 "Sériciculteur"
    459 "Pisciculteur"
    460 "Charbonnier"
    461 "ouvrier qualifié de l'agriculture"
    462 "autres métiers de ce groupe non classés ailleurs"
    463 "Mineur"
    464 "Foreur de puits"
    465 "Carrier"
    466 "Tailleur de pierre"
    467 "Marbrier"
    468 "Creuseur de puits"
    469 "maçon - tâcheron"
    470 "Entrepreneur"
    471 "Ferrailleur"
    472 "Echafaudeur"
    473 "Charpentier"
    474 "Carreleur, poseur revêtement de sol"
    475 "Plafonneur"
    476 "Plâtrier"
    477 "Vitrier"
    478 "Plombier"
    479 "Puisatier"
    480 "Electricien"
    481 "Peintre en bâtiment"
    482 "Peintre, carrosserie"
    483 "Soudeur"
    484 "Chaudronnier"
    485 "Ferblantier"
    486 "Tôlier"
    487 "Forgeron"
    488 "Armurier"
    489 "Serrurier"
    490 "Mécanicien, garagiste"
    491 "Mécanicien, réparateur de petit engin"
    492 "Electromécanicien"
    493 "Dépanneur : récepteur radio et télévision"
    494 "Bijoutier, joaillier, orfèvre"
    495 "Potier"
    496 "Menuisier, Ebéniste, artisan article en bois"
    497 "Vannier / artisan tressage de corbeille"
    498 "Tailleur / brodeur"
    499 "Tisserand"
    500 "Tricoteur"
    501 "Teinturier / artisan du textile"
    502 "Imprimeur"
    503 "Boucher"
    504 "Matelassier"
    505 "Tapissier"
    506 "Tanneur"
    507 "Cordonnier"
    508 "Maroquinier"
    509 "Réparateur de chaussures"
    510 "Dolotière"
    511 "fileuse de coton"
    512 "réparateur de montre - horloger"
    513 "autres métiers de ce groupe non classé ailleurs"
    514 "Conducteur de machine et installation fixe"
    515 "Conducteur de train, locomotive"
    516 "Coursier (cycliste, motocyclette)"
    517 "Conducteur d'autobus et d'autocar"
    518 "Conducteur de camion (citerne, remorque)"
    519 "Conducteur d'engin agricole et forestier"
    520 "Conducteur d'engins de chantier"
    521 "Batelier"
    522 "Matelot"
    523 "Monteur"
    524 "Autres métiers de ce groupe non classé ailleurs"
    525 "Marchand ambulant"
    526 "Colporteur"
    527 "Vendeur de journaux"
    528 "Livreur, distributeur"
    529 "Cireur de chaussure"
    530 "Garçons de courses"
    531 "Laveur ambulant (vitre de voiture)"
    532 "Domestique, bonne, aide ménagère"
    533 "Nettoyeur"
    534 "Plongeur"
    535 "Blanchisseur"
    536 "Concierge"
    537 "Gardien - veilleur de nuit"
    538 "Eboueur"
    539 "Balayeur"
    540 "Ouvrier, manoeuvre agricole"
    541 "Manoeuvre en bâtiment"
    542 "Charretier"
    543 "Docker"
    544 "Autres métiers de ce groupe non classé ailleurs"
    545 "Militaire"
    546 "Gendarme"
    547 "Pompier"
    548 "Agent de la garde nationale"
    549 "Autre personnel de l'armée et de la sécurité"
    600 "Agent de banque"
    601 "Gérant de restaurant"
    602 "Gérant de cabine"
    603 "Apprenti"
    604 "Employé de mairie"
    605 "Répétiteur"
    996 "Autres professions non classées ailleurs"
    997 "Profession non précisée"
    998 "Sans profession"
  /MV717   
      0 "Not working"
      1 "Professional/technical/managerial"
      2 "Clerical"
      3 "Sales"
      4 "Agriculture - self employed"
      5 "Agriculture - employee"
      6 "Household and domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     98 "Don't know"
  /MV719   
      1 "For family member"
      2 "For someone else"
      3 "Self-employed"
  /MV721   
      1 "At home"
      2 "Away"
  /MV731   
      0 "No"
      1 "In the past year"
      2 "Currently working"
  /MV732   
      1 "All year"
      2 "Seasonal"
      3 "Occasional"
  /MV739   
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
  /MV740   
      0 "Own land"
      1 "Family land"
      2 "Someone else's land"
      3 "Rented land"
      8 "Don't know"
  /MV741   
      0 "Not paid"
      1 "Cash only"
      2 "Cash and in-kind"
      3 "In-kind only"
  /MV743A  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Other"
      8 "Don't know/depends"
  /MV743B  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Other"
      8 "Don't know/depends"
  /MV743C  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Decision not made/not applicable"
      8 "Don't know/depends"
  /MV743D  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Decision not made/not applicable"
      8 "Don't know/depends"
  /MV743E  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Decision not made/not applicable"
      8 "Don't know/depends"
  /MV743F  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Decision not made/not applicable"
      8 "Don't know/depends"
  /MV743G  
      1 "Respondent alone"
      2 "Respondent and wife/partner"
      3 "Respondent and other person"
      4 "Wife/partner alone"
      5 "Someone else"
      6 "Decision not made/not applicable"
      8 "Don't know/depends"
  /MV744A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV744B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV744C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV744D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV744E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV745A  
      0 "Does not own"
      1 "Alone only"
      2 "Jointly only"
      3 "Both alone and jointly"
  /MV745B  
      0 "Does not own"
      1 "Alone only"
      2 "Jointly only"
      3 "Both alone and jointly"
  /MV747A  
      0 "Disagree"
      1 "Agree"
      8 "Don't know"
  /MV747B  
      0 "Disagree"
      1 "Agree"
      8 "Don't know"
  /MV750   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV751   
      0 "No"
      1 "Yes"
  /MV754BP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV754CP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV754DP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV754JP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV754WP 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV756   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV761   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV761B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV761C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV762AA 
      0 "No"
      1 "Yes"
  /MV762AB 
      0 "No"
      1 "Yes"
  /MV762AC 
      0 "No"
      1 "Yes"
  /MV762AD 
      0 "No"
      1 "Yes"
  /MV762AE 
      0 "No"
      1 "Yes"
  /MV762AF 
      0 "No"
      1 "Yes"
  /MV762AG 
      0 "No"
      1 "Yes"
  /MV762AH 
      0 "No"
      1 "Yes"
  /MV762AI 
      0 "No"
      1 "Yes"
  /MV762AJ 
      0 "No"
      1 "Yes"
  /MV762AK 
      0 "No"
      1 "Yes"
  /MV762AL 
      0 "No"
      1 "Yes"
  /MV762AM 
      0 "No"
      1 "Yes"
  /MV762AN 
      0 "No"
      1 "Yes"
  /MV762AO 
      0 "No"
      1 "Yes"
  /MV762AP 
      0 "No"
      1 "Yes"
  /MV762AQ 
      0 "No"
      1 "Yes"
  /MV762AR 
      0 "No"
      1 "Yes"
  /MV762AS 
      0 "No"
      1 "Yes"
  /MV762AT 
      0 "No"
      1 "Yes"
  /MV762AU 
      0 "No"
      1 "Yes"
  /MV762AV 
      0 "No"
      1 "Yes"
  /MV762AW 
      0 "No"
      1 "Yes"
  /MV762AX 
      0 "No"
      1 "Yes"
  /MV762AZ 
      0 "No"
      1 "Yes: don't know"
  /MV762BA 
      0 "No"
      1 "Yes"
  /MV762BB 
      0 "No"
      1 "Yes"
  /MV762BC 
      0 "No"
      1 "Yes"
  /MV762BD 
      0 "No"
      1 "Yes"
  /MV762BE 
      0 "No"
      1 "Yes"
  /MV762BF 
      0 "No"
      1 "Yes"
  /MV762BG 
      0 "No"
      1 "Yes"
  /MV762BH 
      0 "No"
      1 "Yes"
  /MV762BI 
      0 "No"
      1 "Yes"
  /MV762BJ 
      0 "No"
      1 "Yes"
  /MV762BK 
      0 "No"
      1 "Yes"
  /MV762BL 
      0 "No"
      1 "Yes"
  /MV762BM 
      0 "No"
      1 "Yes"
  /MV762BN 
      0 "No"
      1 "Yes"
  /MV762BO 
      0 "No"
      1 "Yes"
  /MV762BP 
      0 "No"
      1 "Yes"
  /MV762BQ 
      0 "No"
      1 "Yes"
  /MV762BR 
      0 "No"
      1 "Yes"
  /MV762BS 
      0 "No"
      1 "Yes"
  /MV762BT 
      0 "No"
      1 "Yes"
  /MV762BU 
      0 "No"
      1 "Yes"
  /MV762BV 
      0 "No"
      1 "Yes"
  /MV762BW 
      0 "No"
      1 "Yes"
  /MV762BX 
      0 "No"
      1 "Yes"
  /MV762BZ 
      0 "No"
      1 "Yes: don't know"
  /MV763A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763D  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763E  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763F  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV763G  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV766A  
     98 "Don't know"
  /MV766B  
     98 "Don't know"
  /MV767A  
      1 "Spouse"
      2 "Girlfriend/fiance"
      3 "Other friend"
      4 "Casual acquaintance"
      5 "Relative"
      6 "Commercial sex worker"
      7 "Live-in partner"
     96 "Other"
  /MV767B  
      1 "Spouse"
      2 "Girlfriend/fiance"
      3 "Other friend"
      4 "Casual acquaintance"
      5 "Relative"
      6 "Commercial sex worker"
      7 "Live-in partner"
     96 "Other"
  /MV767C  
      1 "Spouse"
      2 "Girlfriend/fiance"
      3 "Other friend"
      4 "Casual acquaintance"
      5 "Relative"
      6 "Commercial sex worker"
      7 "Live-in partner"
     96 "Other"
  /MV768A  
    101 "Days: 1"
    199 "Days: number missing"
    201 "Months: 1"
    299 "Months: number missing"
    301 "Years: 1"
    399 "Years: number missing"
  /MV768B  
    101 "Days: 1"
    199 "Days: number missing"
    201 "Months: 1"
    299 "Months: number missing"
    301 "Years: 1"
    399 "Years: number missing"
  /MV768C  
    101 "Days: 1"
    199 "Days: number missing"
    201 "Months: 1"
    299 "Months: number missing"
    301 "Years: 1"
    399 "Years: number missing"
  /MV769   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV769A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV770   
      0 "No"
      1 "Yes"
  /MV770A  
      0 "No"
      1 "Yes"
  /MV770B  
      0 "No"
      1 "Yes"
  /MV770C  
      0 "No"
      1 "Yes"
  /MV770D  
      0 "No"
      1 "Yes"
  /MV770E  
      0 "No"
      1 "Yes"
  /MV770F  
      0 "No"
      1 "Yes"
  /MV770G  
      0 "No"
      1 "Yes"
  /MV770H  
      0 "No"
      1 "Yes"
  /MV770I  
      0 "No"
      1 "Yes"
  /MV770J  
      0 "No"
      1 "Yes"
  /MV770K  
      0 "No"
      1 "Yes"
  /MV770L  
      0 "No"
      1 "Yes"
  /MV770M  
      0 "No"
      1 "Yes"
  /MV770N  
      0 "No"
      1 "Yes"
  /MV770O  
      0 "No"
      1 "Yes"
  /MV770P  
      0 "No"
      1 "Yes"
  /MV770Q  
      0 "No"
      1 "Yes"
  /MV770R  
      0 "No"
      1 "Yes"
  /MV770S  
      0 "No"
      1 "Yes"
  /MV770T  
      0 "No"
      1 "Yes"
  /MV770U  
      0 "No"
      1 "Yes"
  /MV770V  
      0 "No"
      1 "Yes"
  /MV770W  
      0 "No"
      1 "Yes"
  /MV770X  
      0 "No"
      1 "Yes"
  /MV774A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV774B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV774C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV775   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV777   
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV778   
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV779   
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV780   
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV781   
      0 "No"
      1 "Yes"
  /MV783   
      0 "No"
      1 "Yes"
  /MV784A  
      0 "No"
      1 "Yes"
  /MV784B  
      0 "No"
      1 "Yes"
  /MV784C  
      0 "No"
      1 "Yes"
  /MV784D  
      0 "No"
      1 "Yes"
  /MV784E  
      0 "No"
      1 "Yes"
  /MV784F  
      0 "No"
      1 "Yes"
  /MV784G  
      0 "No"
      1 "Yes"
  /MV784H  
      0 "No"
      1 "Yes"
  /MV784I  
      0 "No"
      1 "Yes"
  /MV784J  
      0 "No"
      1 "Yes"
  /MV784K  
      0 "No"
      1 "Yes"
  /MV784L  
      0 "No"
      1 "Yes"
  /MV784M  
      0 "No"
      1 "Yes"
  /MV784N  
      0 "No"
      1 "Yes"
  /MV784O  
      0 "No"
      1 "Yes"
  /MV784P  
      0 "No"
      1 "Yes"
  /MV784Q  
      0 "No"
      1 "Yes"
  /MV784R  
      0 "No"
      1 "Yes"
  /MV784S  
      0 "No"
      1 "Yes"
  /MV784T  
      0 "No"
      1 "Yes"
  /MV784U  
      0 "No"
      1 "Yes"
  /MV784V  
      0 "No"
      1 "Yes"
  /MV784X  
      0 "No"
      1 "Yes"
  /MV785   
      0 "No"
      1 "Yes"
  /MV791   
      0 "No"
      1 "Yes"
  /MV793   
      0 "No"
      1 "Yes"
  /MV793A  
      0 "No"
      1 "Yes"
  /MV793B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV820   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV822   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV823   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV824   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV825   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV826   
      1 "Less than 12 months"
      2 "12-23 months"
      3 "2 years or more"
  /MV826A  
     95 "Two or more years"
     98 "Don't know"
  /MV827   
      1 "Asked for the test"
      2 "Offered and accepted"
      3 "Required"
  /MV828   
      0 "No"
      1 "Yes"
  /MV829   
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Stand-alone VCT center"
     14 "Family planning clinic"
     15 "Mobile clinic"
     16 "Field worker"
     17 "School based clinic"
     18 "Other public"
     20 "PRIVATE SECTOR"
     21 "Private hospital/clinic/doctor"
     22 "Private stand-alone VCT center"
     23 "Pharmacy"
     24 "Private mobile clinic"
     25 "Private field worker"
     26 "Private school based clinic"
     27 "Other private medical"
     30 "OTHER"
     31 "Home"
     32 "Correctional facility"
     96 "Other"
  /MV832B  
    100 "<1 day ago"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /MV832C  
    100 "<1 day ago"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /MV833A  
      0 "No"
      1 "Yes"
  /MV833B  
      0 "No"
      1 "Yes"
  /MV833C  
      0 "No"
      1 "Yes"
  /MV834A  
     95 "95+"
     98 "Don't know"
  /MV834B  
     95 "95+"
     98 "Don't know"
  /MV834C  
     95 "95+"
     98 "Don't know"
  /MV835A  
      0 "No"
      1 "Respondent drunk only"
      2 "Partner drunk only"
      3 "Both drunk"
      4 "Neither drunk but consumed alcohol"
  /MV835B  
      0 "No"
      1 "Respondent drunk only"
      2 "Partner drunk only"
      3 "Both drunk"
      4 "Neither drunk but consumed alcohol"
  /MV835C  
      0 "No"
      1 "Respondent drunk only"
      2 "Partner drunk only"
      3 "Both drunk"
      4 "Neither drunk but consumed alcohol"
  /MV836   
     95 "95+"
     98 "Don't know"
  /MV837   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /MV844   
      0 "No"
      1 "Yes"
      8 "Don't know anyone with AIDS"
  /MV845   
      0 "No"
      1 "Yes"
  /MV846   
      0 "No"
      1 "Yes"
  /MV847   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/no opinion"
  /MV848   
      0 "Disagree"
      1 "Agree"
      8 "Don't know/no opinion"
  /MV849   
      0 "No"
      1 "Yes"
      8 "Don't know/depends"
  /MV851A  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851B  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851C  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851D  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851E  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851F  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851G  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851H  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851I  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851J  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851K  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV851L  
      0 "No"
      1 "Yes"
      8 "Don't know/not sure/depends"
  /MV852A  
    100 "Days: 0"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
  /MV852B  
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
  /MV852C  
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
  /MV853A  
     95 "95+"
     98 "Don't know"
  /MV853B  
     95 "95+"
     98 "Don't know"
  /MV853C  
     95 "95+"
     98 "Don't know"
  /MV854A  
      0 "No"
      1 "Yes"
  /MV854B  
      0 "No"
      1 "Yes"
  /MG100   
      0 "No"
      1 "Yes"
  /MG101   
      0 "No"
      1 "Yes"
  /MG117A  
      0 "No"
      1 "Yes"
  /MG117B  
      0 "No"
      1 "Yes"
  /MG117C  
      0 "No"
      1 "Yes"
  /MG117D  
      0 "No"
      1 "Yes"
  /MG117E  
      0 "No"
      1 "Yes"
  /MG117F  
      0 "No"
      1 "Yes"
  /MG117G  
      0 "No"
      1 "Yes"
  /MG117H  
      0 "No"
      1 "Yes"
  /MG117I  
      0 "No"
      1 "Yes"
  /MG117J  
      0 "No"
      1 "Yes"
  /MG117X  
      0 "No"
      1 "Yes"
  /MG117Y  
      0 "No"
      1 "Yes"
  /MG118   
      0 "No"
      1 "Yes"
      3 "No religion"
      8 "Don't know"
  /MG119   
      1 "Continued"
      2 "Stopped"
      3 "Depends"
      8 "Don't know"
  /SM302D  
      0 "No"
      1 "Yes"
  /SM302B1 
      0 "No"
      1 "Yes"
  /SM302B2 
      0 "No"
      1 "Yes"
  /SM302B3 
      0 "No"
      1 "Yes"
  /SM302B4 
      0 "No"
      1 "Yes"
  /SM302C1 
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SM302E1 
      0 "No"
      1 "Yes"
  /SM302E2 
      0 "No"
      1 "Yes"
  /SM302E3 
      0 "No"
      1 "Yes"
  /SM302E4 
      0 "No"
      1 "Yes"
  /SM302G1 
      0 "No"
      1 "Yes"
  /SM302G2 
      0 "No"
      1 "Yes"
  /SM302G3 
      0 "No"
      1 "Yes"
  /SM302G4 
      0 "No"
      1 "Yes"
  /SM402A  
      0 "No"
      1 "Yes"
  /SM707A  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SM707B  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SM707C  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SM707D  
      0 "No"
      1 "Yes"
      8 "Don't know"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\CI62\CIMR62FL.sav'.
